// <auto-generated />
using System;
using Collaboo.App.WebAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Collaboo.App.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181118031938_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Follower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("GitHubRepoUrl");

                    b.Property<int>("OwnerId");

                    b.Property<string>("ProjectName");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new { Id = 1, Description = "Deserunt impedit hic dolorem et delectus eligendi harum iusto.. Blanditiis iure quasi rerum assumenda occaecati excepturi est.. Minus iste odit repellendus nihil cupiditate.. Quisquam quasi at vel aut facere illum praesentium ea.. Consequuntur et deserunt in autem consequuntur amet ipsum qui iusto.. Numquam voluptates magnam voluptate et.. Quod veniam corrupti molestiae cupiditate.. Magnam et fuga dolor inventore impedit nihil similique.. Cupiditate saepe qui est perferendis beatae earum.. Et et optio dicta omnis molestias.. Id ut assumenda ea.. Dolor officiis tenetur.", OwnerId = 60, ProjectName = "damian.info" },
                        new { Id = 2, Description = "Nisi consequuntur praesentium voluptatem.. Expedita eligendi perferendis at omnis tempora enim quibusdam pariatur.. Nemo eum iste cumque id praesentium dolor.. Earum corporis corrupti.. Est itaque quibusdam nihil tempore et.. Sunt autem sequi tempore eius saepe illum ratione placeat.. Ut dolores minima sit.", OwnerId = 31, ProjectName = "lula.net" },
                        new { Id = 3, Description = "Quam impedit dolorem ipsa sint quisquam vel incidunt.. Beatae inventore suscipit.. Ut accusantium omnis est sequi nesciunt suscipit.. Sint ipsam et debitis in ipsum quia aspernatur laboriosam.. Accusantium possimus doloremque quas et.. Facere quidem hic quo nam est quasi eligendi officiis doloribus.. Aliquam similique sed quos est sit quo et qui.. Neque sed omnis ipsum magni cumque repellendus doloremque.. Occaecati voluptas a quo voluptatem sint non.. Qui qui et quod consequatur velit.. Tenetur non aut et quam nihil.. Consequatur libero amet officia.. Qui libero provident architecto veniam distinctio exercitationem.. Earum ullam qui excepturi reiciendis in.. Optio ex voluptatem repellat nesciunt impedit ipsum eius animi.", OwnerId = 90, ProjectName = "wilson.name" },
                        new { Id = 4, Description = "Quo quis et iusto asperiores.. Eum est quasi sapiente beatae impedit earum dignissimos expedita.. Nostrum dolorem sit officia dolores est occaecati consectetur molestiae.. Tempora ducimus non dolor ullam ab eos qui odit.. Beatae beatae voluptatibus.. Consequatur dicta veniam consectetur sint ducimus assumenda.. Error et animi nesciunt deserunt error eum amet.", OwnerId = 77, ProjectName = "jaida.com" },
                        new { Id = 5, Description = "Vel cum saepe distinctio accusantium sunt quibusdam.. Facilis quisquam numquam voluptas et.. Voluptate consequatur sit enim reiciendis quae et.. Consequuntur in eos praesentium in enim sint et dolorum quasi.. Alias et voluptate reprehenderit provident necessitatibus debitis ut reprehenderit.. Vitae iure voluptatem nesciunt voluptatibus quam qui odio amet doloremque.. Dicta quos omnis ipsam.", OwnerId = 52, ProjectName = "keshawn.org" },
                        new { Id = 6, Description = "Ea aut ratione eaque et a.. Aut et eum aspernatur architecto aut delectus quae amet qui.. Mollitia necessitatibus aspernatur aut et.. Libero sint dolores.. Beatae aut voluptatem aut corrupti ut sint voluptatibus et.. Qui accusantium nihil nulla rerum.. Recusandae inventore aut cupiditate quas consequuntur cumque enim in.. Quia animi libero odit consequatur excepturi qui.. Eveniet temporibus veritatis numquam.. Eos qui veritatis rerum sed similique sunt.. Magnam neque et aut laborum earum.. Ex hic enim ab atque saepe est.", OwnerId = 92, ProjectName = "elvis.com" },
                        new { Id = 7, Description = "Sed veniam hic pariatur.. Porro totam quo quasi odio sit neque cumque.. Quia architecto iusto ipsa alias possimus sunt non repellendus.. Voluptatum aut minus optio quos ut facere consequatur dolorum aliquid.. Amet ullam ipsam rerum eum.. Odit ut repudiandae assumenda.. Ut et assumenda in.. Ut dolores nesciunt facilis doloribus dolores.. Quis minus maiores.. Nisi provident est quis ut aliquid praesentium itaque est.. Nesciunt et laborum.. Tempore officiis dolor voluptas nam beatae.. Sint veritatis atque cum praesentium impedit autem eligendi exercitationem earum.. In quis omnis consequatur.. Qui est repellat consectetur.. Et ex aut sint unde quia voluptatem dolorum dolorem.. Quasi et nulla.. Totam quia optio beatae rerum vitae.. Deleniti sit consequatur eius.", OwnerId = 24, ProjectName = "meghan.name" },
                        new { Id = 8, Description = "Quisquam nam rerum explicabo sed impedit autem nesciunt repudiandae.. Inventore quasi totam eveniet vitae quos non.. Ut sit cumque non ex.. Officia voluptatem quia.. Exercitationem enim rem.. Ut quae quia ea sit placeat enim omnis.. Sed dolorem aut accusantium quia aut quis molestiae est.. Quis consequuntur quidem vitae adipisci enim omnis molestias.. Sed enim eos animi veritatis voluptate aspernatur quam sunt.. Rem omnis voluptatem omnis sit neque ea et.. Velit nemo rerum.. Sunt mollitia aspernatur cupiditate.. Delectus magni sunt et et.. Modi natus tempore error ab dolorum architecto.. Quo dolore magnam recusandae aliquid aliquid qui.", OwnerId = 92, ProjectName = "rita.com" },
                        new { Id = 9, Description = "Corrupti est explicabo.. Consequatur delectus aut voluptas blanditiis.. Officia incidunt sed molestias omnis fuga.. Quibusdam adipisci laudantium suscipit porro quia.. Voluptatem nam maxime quia rerum ab exercitationem accusantium perspiciatis qui.. In totam eum.. Vitae id enim dolores ut distinctio voluptatem.. Voluptas quibusdam eum molestiae eaque accusamus.. Omnis assumenda rem neque.. Laboriosam eius impedit aut voluptate ratione natus nobis reprehenderit deleniti.. Sequi odit ut aut est voluptatem qui voluptates enim exercitationem.. Ut autem illo dolorum quaerat.. Enim eum quaerat odit.. Velit eius et doloremque molestiae.. Sed aspernatur suscipit aut commodi qui tempore voluptatem.. Possimus molestias id amet error necessitatibus cum beatae ipsam.", OwnerId = 34, ProjectName = "reva.net" },
                        new { Id = 10, Description = "Quis aut eius officiis at optio.. Dolore eligendi mollitia.. Temporibus quia sapiente aliquam ut iste eum corporis blanditiis.. Et facilis architecto ut velit minus.. Unde cumque id earum.. Est delectus alias ratione.. Illum dolorum temporibus excepturi illum qui sit omnis porro porro.. Omnis est odio atque et aut similique commodi qui.. Odio sapiente officiis cumque asperiores.. Voluptates iste atque asperiores aliquam qui est error soluta libero.. Maiores et maxime voluptas optio sit voluptatem est molestiae neque.. Et soluta qui quidem alias et.. Expedita repudiandae vel qui sequi quam.. Incidunt quisquam sunt eum.. Debitis aut omnis consequuntur.. Et in similique maxime rerum omnis non.. Dolorem qui possimus.. Animi et reprehenderit doloribus amet voluptatem facere quasi dolorem.. Voluptas perspiciatis laudantium ullam placeat.", OwnerId = 39, ProjectName = "niko.biz" },
                        new { Id = 11, Description = "Omnis vel assumenda.. Ab quidem quo commodi rerum facere voluptas.. Praesentium molestiae sed tenetur doloribus quia est dolor aut illo.. Occaecati architecto voluptatem minima facilis aut.. Enim ut autem quisquam magnam temporibus nulla.. Earum omnis nemo reprehenderit amet esse sit ex vitae.. Dolor autem in.. Mollitia officiis accusantium et qui magnam non.. Ex quasi iste.. Odio repellendus quia quod quia.. Odit velit ut eos voluptatum.. Et alias et porro earum et laudantium.. Qui qui rerum.. Eligendi facere reprehenderit mollitia quaerat sint adipisci labore fugiat voluptas.. Incidunt sit nisi eos pariatur est velit ut blanditiis in.", OwnerId = 41, ProjectName = "loraine.info" },
                        new { Id = 12, Description = "Dicta fugit id unde sed impedit voluptas aliquam quae.. Itaque molestias itaque voluptatem rerum labore.. Voluptatem accusantium enim provident mollitia vel et quia earum.. Corrupti occaecati quis sed repellat pariatur.. Eum vitae harum quis rerum ut.. Non exercitationem iusto voluptates dolor quaerat.. Excepturi neque fuga.. Consequatur deleniti minima corrupti minus doloribus modi.. Voluptas aliquid minus omnis nemo.. Distinctio quos corrupti et id dolores eum possimus debitis id.. Rerum nihil qui soluta aliquid.. Ea distinctio molestias harum consequatur dolorem laboriosam ut rerum veritatis.. Earum eaque velit sed magni ut.. Assumenda ut est iste magni tempora est.. Cum amet temporibus quis vitae culpa aut.. Quis aut quibusdam nemo exercitationem.", OwnerId = 33, ProjectName = "caleigh.name" },
                        new { Id = 13, Description = "Consequatur illum quo voluptate voluptas illum.. Et repudiandae vel sit et non veniam accusantium.. Corrupti sequi natus ex voluptatibus quibusdam ut nam dolorem.. Sit nam modi dignissimos reprehenderit magni.. Cumque eius temporibus voluptas enim nihil aut.. Blanditiis libero nesciunt quae similique sunt sint.. Non quo asperiores a est.. Non nulla ipsum culpa sit atque.. Ea rem quam.. Non eum veritatis ut.. Eius qui officia.. Non magni consequatur dolorum aliquam eos vel eum optio.. Qui quia voluptatibus magnam aut rerum deserunt.. Sunt corrupti corrupti ab adipisci quod nulla ea.. Blanditiis quae cupiditate et ut quis consequatur et.. Aperiam omnis quia.. Tempore nobis impedit et voluptatem accusantium.. In ab nostrum voluptate.. Rerum aspernatur ipsam voluptatum recusandae quasi est.. Sed ex suscipit ipsum doloribus magni et ipsum sit non.", OwnerId = 91, ProjectName = "ally.info" },
                        new { Id = 14, Description = "Et nisi sit porro qui dolores dolorem ea possimus.. Sunt et enim.. Dignissimos ratione delectus omnis molestiae ut.. Ut sed officiis necessitatibus modi.. Et quia vel.. Nesciunt perferendis quis excepturi magni.. Ex tenetur omnis hic hic culpa illo.. Quas non cum rerum repellendus rerum ut itaque ad dolores.. Aut blanditiis dolorem mollitia vitae et.. Autem facere non laborum maiores.. Enim ut laborum dolorem libero in commodi assumenda atque aut.. Optio vel ea suscipit iusto aspernatur.. Quod temporibus inventore voluptas.. Non ex cum doloremque.", OwnerId = 67, ProjectName = "concepcion.biz" },
                        new { Id = 15, Description = "Perspiciatis est sunt et sit odio enim debitis dolores nobis.. Atque dignissimos ut nihil error.. Earum et impedit accusamus adipisci molestiae maiores qui dicta totam.. Consequatur optio error amet repellat quos voluptatem est repellendus explicabo.. Expedita hic et.. Autem consequatur distinctio dicta blanditiis aut laudantium porro.. Facilis ut voluptatem ut voluptas.. Nulla dolore aut veniam molestias iusto sed.. Corrupti hic placeat sit.. At quo asperiores possimus consequatur ut unde voluptatibus minus.. Perferendis perferendis et.. Corporis ut minus totam aut molestiae adipisci dolore at nobis.. Ex modi quaerat accusamus quia dolores nihil a.. Eos molestiae et molestias perferendis aut numquam est.. Dolore sapiente ut.. Blanditiis vel mollitia possimus atque rerum explicabo.. Est voluptatibus enim explicabo et voluptatem nostrum.. Natus et nemo.. Modi sed debitis.. Modi qui repellat impedit officia dolores id est in facere.", OwnerId = 77, ProjectName = "immanuel.biz" },
                        new { Id = 16, Description = "Omnis et aspernatur aliquam dignissimos nisi esse commodi.. Molestiae dolores omnis eum et quia.. Suscipit itaque impedit provident doloremque hic.. Asperiores voluptatum autem qui optio eveniet.. Nulla quo qui numquam unde adipisci consequuntur.. Et unde consequatur sunt molestias repellendus explicabo culpa modi.. Consectetur autem et.. Error rerum dolorum consequatur deleniti aut dolor.. Possimus quisquam totam.. Beatae expedita velit dolorem odit perferendis magnam voluptatum quas neque.. Itaque odio animi ut saepe sequi sint quas.", OwnerId = 53, ProjectName = "bonita.info" },
                        new { Id = 17, Description = "Mollitia id quo accusantium vitae.. Temporibus sunt fuga sunt nihil.. Ipsum inventore delectus quia consequuntur a.. Ea neque soluta.. Aut velit rerum repudiandae labore.. Rerum vel id eum.. Sunt consequatur corporis modi.. Eos quis quidem ipsam et saepe.. Est explicabo unde sit qui dolorem.", OwnerId = 35, ProjectName = "sanford.com" },
                        new { Id = 18, Description = "Fugiat dolorem velit blanditiis omnis.. Cum omnis ut illo perferendis corrupti mollitia officiis ut error.. Aperiam cupiditate consequatur molestias maiores id neque illum eligendi.. Omnis est reprehenderit sint inventore expedita alias totam in adipisci.. Qui omnis quidem aut et voluptate impedit est.. Praesentium quos animi deleniti fugiat similique perspiciatis eos nulla dicta.. Rerum vero asperiores.. Fugit in ut tenetur.. Mollitia ea quas quis sit numquam voluptas qui ea.. Sit qui quia.. Nihil inventore quae repudiandae soluta corrupti fugit qui.. Enim nesciunt eaque sapiente assumenda molestias doloribus.. Et facere dolor ea illo.. Tempora exercitationem dolorum aut vel blanditiis repellendus possimus qui et.. Similique et et.. Vero totam porro qui dolor consectetur numquam qui.. Repellat eius velit porro laudantium.. Molestiae vel quis quasi qui et veritatis nobis.. Nobis quo iste sunt est.", OwnerId = 84, ProjectName = "colin.info" },
                        new { Id = 19, Description = "Aut quis et et enim quibusdam perferendis sequi.. Aut deserunt quae et nostrum.. Consequatur quod adipisci asperiores dolore quae autem dolor esse assumenda.. Quidem rerum sed esse quibusdam omnis atque eaque blanditiis voluptate.. Voluptatum aspernatur ad aut laudantium.. Debitis nihil quidem est voluptatem nobis animi aspernatur.. Ducimus soluta quidem.. Molestias est eos voluptas.. Quis et hic aut.. Error accusantium quo deleniti facilis ut aspernatur quisquam odio.. Aspernatur ut quo magni ipsum autem a.. Ipsam autem sit et ea labore ut quo suscipit est.. Et pariatur placeat.. Rerum architecto maxime nihil sed tenetur fugiat et est.. Illo sed id recusandae.. Sequi repellendus esse.. Quidem eius atque omnis fuga mollitia culpa recusandae.. Voluptas id aut qui aliquid aperiam dolorem illo molestiae hic.. Maiores atque rerum id natus ut quia exercitationem dolor.", OwnerId = 33, ProjectName = "lexie.biz" },
                        new { Id = 20, Description = "Aut et ea enim.. Dolorem fuga sit.. Culpa quia incidunt quia assumenda sunt odit tenetur est fugiat.. Optio voluptatem sit debitis sed minima voluptatum veniam.. Id impedit ad doloribus.", OwnerId = 57, ProjectName = "dave.info" },
                        new { Id = 21, Description = "Enim quia dolores delectus culpa nemo atque voluptas.. Ex est tempore.. Necessitatibus dolores ea voluptatum sapiente.. Cupiditate aut voluptas aliquid laboriosam.. Ullam accusamus pariatur labore omnis provident consectetur nobis quia.. Quo cupiditate qui sunt accusantium qui.. Aliquam sed iste deleniti incidunt illum omnis harum dicta.. Veritatis ut quidem totam assumenda.. Aspernatur veniam iusto quidem dicta quaerat dolorem sed doloribus.. Voluptatum repellendus quo maxime.. Exercitationem magni labore qui ut repellendus.", OwnerId = 39, ProjectName = "annetta.com" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProjectId");

                    b.Property<int>("Rating");

                    b.Property<int>("SkillId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectRequirments");

                    b.HasData(
                        new { Id = 1, Rating = 1, SkillId = 15 },
                        new { Id = 2, Rating = 4, SkillId = 6 },
                        new { Id = 3, Rating = 1, SkillId = 18 },
                        new { Id = 4, Rating = 3, SkillId = 22 },
                        new { Id = 5, Rating = 5, SkillId = 17 },
                        new { Id = 6, Rating = 4, SkillId = 7 },
                        new { Id = 7, Rating = 3, SkillId = 18 },
                        new { Id = 8, Rating = 4, SkillId = 23 },
                        new { Id = 9, Rating = 2, SkillId = 1 },
                        new { Id = 10, Rating = 3, SkillId = 2 },
                        new { Id = 11, Rating = 2, SkillId = 23 },
                        new { Id = 12, Rating = 4, SkillId = 8 },
                        new { Id = 13, Rating = 5, SkillId = 18 },
                        new { Id = 14, Rating = 4, SkillId = 10 },
                        new { Id = 15, Rating = 5, SkillId = 13 },
                        new { Id = 16, Rating = 1, SkillId = 17 },
                        new { Id = 17, Rating = 2, SkillId = 9 },
                        new { Id = 18, Rating = 3, SkillId = 12 },
                        new { Id = 19, Rating = 3, SkillId = 14 },
                        new { Id = 20, Rating = 3, SkillId = 5 },
                        new { Id = 21, Rating = 3, SkillId = 13 }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SkillName");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new { Id = 1, SkillName = "C#" },
                        new { Id = 2, SkillName = "Haskel" },
                        new { Id = 3, SkillName = "Swift" },
                        new { Id = 4, SkillName = "Java" },
                        new { Id = 5, SkillName = "R" },
                        new { Id = 6, SkillName = "PHP" },
                        new { Id = 7, SkillName = "Assembly" },
                        new { Id = 8, SkillName = "Go" },
                        new { Id = 9, SkillName = "Ruby" },
                        new { Id = 10, SkillName = "Perl" },
                        new { Id = 11, SkillName = "MS-SQL" },
                        new { Id = 12, SkillName = "JavaScript" },
                        new { Id = 13, SkillName = "TypeScript" },
                        new { Id = 14, SkillName = "C" },
                        new { Id = 15, SkillName = "C++" },
                        new { Id = 16, SkillName = "Python" },
                        new { Id = 17, SkillName = "PL/SQL" },
                        new { Id = 18, SkillName = "MongoDb" },
                        new { Id = 19, SkillName = "Lisp" },
                        new { Id = 20, SkillName = "Prolog" },
                        new { Id = 21, SkillName = "D" },
                        new { Id = 22, SkillName = "Rust" },
                        new { Id = 23, SkillName = "Android" },
                        new { Id = 24, SkillName = ".Net" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<int>("GitHubId");

                    b.Property<string>("Login");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, GitHubId = 0, Login = "Enos_DuBuque82" },
                        new { Id = 2, GitHubId = 0, Login = "Bianka_Leannon5" },
                        new { Id = 3, GitHubId = 0, Login = "Abigayle.Bayer" },
                        new { Id = 4, GitHubId = 0, Login = "Enrico_Kuvalis" },
                        new { Id = 5, GitHubId = 0, Login = "Jamir.Hand90" },
                        new { Id = 6, GitHubId = 0, Login = "Lia.Cummerata32" },
                        new { Id = 7, GitHubId = 0, Login = "Cathrine96" },
                        new { Id = 8, GitHubId = 0, Login = "Dimitri39" },
                        new { Id = 9, GitHubId = 0, Login = "Margie_Dickens95" },
                        new { Id = 10, GitHubId = 0, Login = "Immanuel_Buckridge46" },
                        new { Id = 11, GitHubId = 0, Login = "Polly_Erdman57" },
                        new { Id = 12, GitHubId = 0, Login = "Stephan.Auer10" },
                        new { Id = 13, GitHubId = 0, Login = "Eliezer_Gleason68" },
                        new { Id = 14, GitHubId = 0, Login = "Claude.OKeefe4" },
                        new { Id = 15, GitHubId = 0, Login = "Osbaldo93" },
                        new { Id = 16, GitHubId = 0, Login = "Reynold_Fadel36" },
                        new { Id = 17, GitHubId = 0, Login = "Jose76" },
                        new { Id = 18, GitHubId = 0, Login = "Maya65" },
                        new { Id = 19, GitHubId = 0, Login = "Coty94" },
                        new { Id = 20, GitHubId = 0, Login = "Keanu9" },
                        new { Id = 21, GitHubId = 0, Login = "Hailie15" },
                        new { Id = 22, GitHubId = 0, Login = "Nona_Schamberger" },
                        new { Id = 23, GitHubId = 0, Login = "Raina97" },
                        new { Id = 24, GitHubId = 0, Login = "Naomie_Christiansen" },
                        new { Id = 25, GitHubId = 0, Login = "Godfrey.Hauck" },
                        new { Id = 26, GitHubId = 0, Login = "Danielle_Kuphal47" },
                        new { Id = 27, GitHubId = 0, Login = "Kailey92" },
                        new { Id = 28, GitHubId = 0, Login = "Austyn.Fadel83" },
                        new { Id = 29, GitHubId = 0, Login = "Hazle.Quigley60" },
                        new { Id = 30, GitHubId = 0, Login = "Monica95" },
                        new { Id = 31, GitHubId = 0, Login = "Aglae91" },
                        new { Id = 32, GitHubId = 0, Login = "Arnold55" },
                        new { Id = 33, GitHubId = 0, Login = "Dakota86" },
                        new { Id = 34, GitHubId = 0, Login = "Talia67" },
                        new { Id = 35, GitHubId = 0, Login = "Danial86" },
                        new { Id = 36, GitHubId = 0, Login = "Meta74" },
                        new { Id = 37, GitHubId = 0, Login = "Stone.Rath" },
                        new { Id = 38, GitHubId = 0, Login = "Timmothy.Renner95" },
                        new { Id = 39, GitHubId = 0, Login = "Kamryn.Will62" },
                        new { Id = 40, GitHubId = 0, Login = "Forest_Connelly0" },
                        new { Id = 41, GitHubId = 0, Login = "Norbert_Fay16" },
                        new { Id = 42, GitHubId = 0, Login = "Maiya.Schiller" },
                        new { Id = 43, GitHubId = 0, Login = "Jeanie55" },
                        new { Id = 44, GitHubId = 0, Login = "Rahul37" },
                        new { Id = 45, GitHubId = 0, Login = "Ismael.Dach" },
                        new { Id = 46, GitHubId = 0, Login = "Dora.Osinski58" },
                        new { Id = 47, GitHubId = 0, Login = "Howell_Kemmer" },
                        new { Id = 48, GitHubId = 0, Login = "Alysson46" },
                        new { Id = 49, GitHubId = 0, Login = "Hermann.Langosh48" },
                        new { Id = 50, GitHubId = 0, Login = "Fernando_Collins" },
                        new { Id = 51, GitHubId = 0, Login = "Rosalyn40" },
                        new { Id = 52, GitHubId = 0, Login = "Abigayle_Rolfson" },
                        new { Id = 53, GitHubId = 0, Login = "Mateo_Marvin49" },
                        new { Id = 54, GitHubId = 0, Login = "Keaton58" },
                        new { Id = 55, GitHubId = 0, Login = "Daniella.Herzog43" },
                        new { Id = 56, GitHubId = 0, Login = "Eda38" },
                        new { Id = 57, GitHubId = 0, Login = "William96" },
                        new { Id = 58, GitHubId = 0, Login = "Ray76" },
                        new { Id = 59, GitHubId = 0, Login = "Reyna18" },
                        new { Id = 60, GitHubId = 0, Login = "Hilma_Parker35" },
                        new { Id = 61, GitHubId = 0, Login = "Kathlyn_Franecki95" },
                        new { Id = 62, GitHubId = 0, Login = "Serena.Bergnaum77" },
                        new { Id = 63, GitHubId = 0, Login = "Keyshawn.Brekke" },
                        new { Id = 64, GitHubId = 0, Login = "Dakota_Hagenes" },
                        new { Id = 65, GitHubId = 0, Login = "Kaela_Schuppe43" },
                        new { Id = 66, GitHubId = 0, Login = "Gabriel_Reichert6" },
                        new { Id = 67, GitHubId = 0, Login = "Graham_Schinner39" },
                        new { Id = 68, GitHubId = 0, Login = "Arne.Rice44" },
                        new { Id = 69, GitHubId = 0, Login = "Alessandro6" },
                        new { Id = 70, GitHubId = 0, Login = "Martine_Quitzon" },
                        new { Id = 71, GitHubId = 0, Login = "Heidi_Carroll80" },
                        new { Id = 72, GitHubId = 0, Login = "Tanner63" },
                        new { Id = 73, GitHubId = 0, Login = "Payton.Schulist" },
                        new { Id = 74, GitHubId = 0, Login = "Dallin_Dietrich33" },
                        new { Id = 75, GitHubId = 0, Login = "Bailee.Sawayn52" },
                        new { Id = 76, GitHubId = 0, Login = "Gino74" },
                        new { Id = 77, GitHubId = 0, Login = "Estevan.Rau" },
                        new { Id = 78, GitHubId = 0, Login = "Modesta31" },
                        new { Id = 79, GitHubId = 0, Login = "Kendra_Effertz" },
                        new { Id = 80, GitHubId = 0, Login = "Novella44" },
                        new { Id = 81, GitHubId = 0, Login = "Trudie.Auer" },
                        new { Id = 82, GitHubId = 0, Login = "Raegan56" },
                        new { Id = 83, GitHubId = 0, Login = "Florine_Monahan9" },
                        new { Id = 84, GitHubId = 0, Login = "Larry_Koepp17" },
                        new { Id = 85, GitHubId = 0, Login = "Bobby_Kohler8" },
                        new { Id = 86, GitHubId = 0, Login = "Orie_Corwin78" },
                        new { Id = 87, GitHubId = 0, Login = "Wilfrid.Heathcote" },
                        new { Id = 88, GitHubId = 0, Login = "Jermey.Swift" },
                        new { Id = 89, GitHubId = 0, Login = "Laurianne.Wehner60" },
                        new { Id = 90, GitHubId = 0, Login = "Avis1" },
                        new { Id = 91, GitHubId = 0, Login = "Bianka_Emard81" },
                        new { Id = 92, GitHubId = 0, Login = "Felicity75" },
                        new { Id = 93, GitHubId = 0, Login = "Jarvis_Erdman8" },
                        new { Id = 94, GitHubId = 0, Login = "Stacey58" },
                        new { Id = 95, GitHubId = 0, Login = "Aglae45" },
                        new { Id = 96, GitHubId = 0, Login = "Dallin11" },
                        new { Id = 97, GitHubId = 0, Login = "Maximus_Ferry87" },
                        new { Id = 98, GitHubId = 0, Login = "Adolphus.Wiza69" },
                        new { Id = 99, GitHubId = 0, Login = "Magali99" },
                        new { Id = 100, GitHubId = 0, Login = "Myrtie.Frami36" },
                        new { Id = 101, GitHubId = 0, Login = "Ila.Schneider95" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserFollowers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FollowerId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.ToTable("UserFollowers");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Rating");

                    b.Property<int>("SkillId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");

                    b.HasData(
                        new { Id = 1, Rating = 2, SkillId = 12, UserId = 1 },
                        new { Id = 2, Rating = 4, SkillId = 20, UserId = 2 },
                        new { Id = 3, Rating = 4, SkillId = 16, UserId = 3 },
                        new { Id = 4, Rating = 5, SkillId = 23, UserId = 4 },
                        new { Id = 5, Rating = 4, SkillId = 17, UserId = 5 },
                        new { Id = 6, Rating = 4, SkillId = 9, UserId = 6 },
                        new { Id = 7, Rating = 3, SkillId = 21, UserId = 7 },
                        new { Id = 8, Rating = 4, SkillId = 5, UserId = 8 },
                        new { Id = 9, Rating = 5, SkillId = 1, UserId = 9 },
                        new { Id = 10, Rating = 1, SkillId = 5, UserId = 10 },
                        new { Id = 11, Rating = 4, SkillId = 7, UserId = 11 },
                        new { Id = 12, Rating = 3, SkillId = 1, UserId = 12 },
                        new { Id = 13, Rating = 3, SkillId = 3, UserId = 13 },
                        new { Id = 14, Rating = 4, SkillId = 19, UserId = 14 },
                        new { Id = 15, Rating = 4, SkillId = 15, UserId = 15 },
                        new { Id = 16, Rating = 2, SkillId = 20, UserId = 16 },
                        new { Id = 17, Rating = 2, SkillId = 20, UserId = 17 },
                        new { Id = 18, Rating = 3, SkillId = 9, UserId = 18 },
                        new { Id = 19, Rating = 2, SkillId = 4, UserId = 19 },
                        new { Id = 20, Rating = 1, SkillId = 9, UserId = 20 },
                        new { Id = 21, Rating = 4, SkillId = 17, UserId = 21 },
                        new { Id = 22, Rating = 2, SkillId = 11, UserId = 22 },
                        new { Id = 23, Rating = 2, SkillId = 9, UserId = 23 },
                        new { Id = 24, Rating = 5, SkillId = 20, UserId = 24 },
                        new { Id = 25, Rating = 4, SkillId = 4, UserId = 25 },
                        new { Id = 26, Rating = 3, SkillId = 18, UserId = 26 },
                        new { Id = 27, Rating = 4, SkillId = 20, UserId = 27 },
                        new { Id = 28, Rating = 2, SkillId = 1, UserId = 28 },
                        new { Id = 29, Rating = 1, SkillId = 16, UserId = 29 },
                        new { Id = 30, Rating = 2, SkillId = 14, UserId = 30 },
                        new { Id = 31, Rating = 5, SkillId = 4, UserId = 31 },
                        new { Id = 32, Rating = 2, SkillId = 1, UserId = 32 },
                        new { Id = 33, Rating = 2, SkillId = 19, UserId = 33 },
                        new { Id = 34, Rating = 1, SkillId = 14, UserId = 34 },
                        new { Id = 35, Rating = 2, SkillId = 6, UserId = 35 },
                        new { Id = 36, Rating = 5, SkillId = 19, UserId = 36 },
                        new { Id = 37, Rating = 5, SkillId = 16, UserId = 37 },
                        new { Id = 38, Rating = 3, SkillId = 1, UserId = 38 },
                        new { Id = 39, Rating = 5, SkillId = 22, UserId = 39 },
                        new { Id = 40, Rating = 4, SkillId = 4, UserId = 40 },
                        new { Id = 41, Rating = 2, SkillId = 20, UserId = 41 },
                        new { Id = 42, Rating = 1, SkillId = 12, UserId = 42 },
                        new { Id = 43, Rating = 1, SkillId = 13, UserId = 43 },
                        new { Id = 44, Rating = 1, SkillId = 9, UserId = 44 },
                        new { Id = 45, Rating = 3, SkillId = 13, UserId = 45 },
                        new { Id = 46, Rating = 2, SkillId = 15, UserId = 46 },
                        new { Id = 47, Rating = 5, SkillId = 12, UserId = 47 },
                        new { Id = 48, Rating = 3, SkillId = 13, UserId = 48 },
                        new { Id = 49, Rating = 2, SkillId = 9, UserId = 49 },
                        new { Id = 50, Rating = 1, SkillId = 13, UserId = 50 },
                        new { Id = 51, Rating = 2, SkillId = 6, UserId = 51 },
                        new { Id = 52, Rating = 3, SkillId = 13, UserId = 52 },
                        new { Id = 53, Rating = 2, SkillId = 16, UserId = 53 },
                        new { Id = 54, Rating = 5, SkillId = 3, UserId = 54 },
                        new { Id = 55, Rating = 2, SkillId = 6, UserId = 55 },
                        new { Id = 56, Rating = 1, SkillId = 4, UserId = 56 },
                        new { Id = 57, Rating = 5, SkillId = 4, UserId = 57 },
                        new { Id = 58, Rating = 2, SkillId = 3, UserId = 58 },
                        new { Id = 59, Rating = 1, SkillId = 19, UserId = 59 },
                        new { Id = 60, Rating = 5, SkillId = 20, UserId = 60 },
                        new { Id = 61, Rating = 4, SkillId = 19, UserId = 61 },
                        new { Id = 62, Rating = 5, SkillId = 18, UserId = 62 },
                        new { Id = 63, Rating = 5, SkillId = 6, UserId = 63 },
                        new { Id = 64, Rating = 5, SkillId = 11, UserId = 64 },
                        new { Id = 65, Rating = 2, SkillId = 23, UserId = 65 },
                        new { Id = 66, Rating = 4, SkillId = 13, UserId = 66 },
                        new { Id = 67, Rating = 5, SkillId = 4, UserId = 67 },
                        new { Id = 68, Rating = 5, SkillId = 1, UserId = 68 },
                        new { Id = 69, Rating = 2, SkillId = 11, UserId = 69 },
                        new { Id = 70, Rating = 2, SkillId = 12, UserId = 70 },
                        new { Id = 71, Rating = 4, SkillId = 22, UserId = 71 },
                        new { Id = 72, Rating = 1, SkillId = 9, UserId = 72 },
                        new { Id = 73, Rating = 3, SkillId = 3, UserId = 73 },
                        new { Id = 74, Rating = 4, SkillId = 16, UserId = 74 },
                        new { Id = 75, Rating = 1, SkillId = 8, UserId = 75 },
                        new { Id = 76, Rating = 2, SkillId = 13, UserId = 76 },
                        new { Id = 77, Rating = 3, SkillId = 6, UserId = 77 },
                        new { Id = 78, Rating = 4, SkillId = 11, UserId = 78 },
                        new { Id = 79, Rating = 2, SkillId = 17, UserId = 79 },
                        new { Id = 80, Rating = 3, SkillId = 1, UserId = 80 },
                        new { Id = 81, Rating = 4, SkillId = 9, UserId = 81 },
                        new { Id = 82, Rating = 5, SkillId = 9, UserId = 82 },
                        new { Id = 83, Rating = 3, SkillId = 13, UserId = 83 },
                        new { Id = 84, Rating = 2, SkillId = 20, UserId = 84 },
                        new { Id = 85, Rating = 2, SkillId = 8, UserId = 85 },
                        new { Id = 86, Rating = 4, SkillId = 16, UserId = 86 },
                        new { Id = 87, Rating = 4, SkillId = 8, UserId = 87 },
                        new { Id = 88, Rating = 1, SkillId = 19, UserId = 88 },
                        new { Id = 89, Rating = 4, SkillId = 15, UserId = 89 },
                        new { Id = 90, Rating = 2, SkillId = 20, UserId = 90 },
                        new { Id = 91, Rating = 3, SkillId = 7, UserId = 91 },
                        new { Id = 92, Rating = 2, SkillId = 22, UserId = 92 },
                        new { Id = 93, Rating = 3, SkillId = 2, UserId = 93 },
                        new { Id = 94, Rating = 1, SkillId = 16, UserId = 94 },
                        new { Id = 95, Rating = 2, SkillId = 12, UserId = 95 },
                        new { Id = 96, Rating = 4, SkillId = 15, UserId = 96 },
                        new { Id = 97, Rating = 5, SkillId = 5, UserId = 97 },
                        new { Id = 98, Rating = 5, SkillId = 8, UserId = 98 },
                        new { Id = 99, Rating = 1, SkillId = 16, UserId = 99 },
                        new { Id = 100, Rating = 4, SkillId = 22, UserId = 100 },
                        new { Id = 101, Rating = 5, SkillId = 19, UserId = 101 }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectMember", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collaboo.App.WebAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectRequirement", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Project")
                        .WithMany("Requirements")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Collaboo.App.WebAPI.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserFollowers", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Follower", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserSkills", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collaboo.App.WebAPI.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
