// <auto-generated />
using System;
using Collaboo.App.WebAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Collaboo.App.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181118024622_SeedMigration")]
    partial class SeedMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Follower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("GitHubRepoUrl");

                    b.Property<int>("OwnerId");

                    b.Property<string>("ProjectName");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new { Id = 1, Description = @"Est et autem nobis.
Assumenda placeat harum consequatur labore molestias quia.
Iste animi vitae nihil quis.
Velit aliquam minima hic beatae ut fugiat esse quia.
Harum ea dolores sint sunt ab omnis accusantium sed.
Velit quia eum voluptate dolores eos.", OwnerId = 61, ProjectName = "adrianna.name" },
                        new { Id = 2, Description = @"Quaerat ut molestiae impedit molestiae velit nam ullam esse.
Ex fuga omnis minus debitis quis nostrum quibusdam.
Dolorem illo nemo necessitatibus deserunt ut accusamus.
Illum itaque distinctio qui ut eligendi consequatur quis aut.
Quia facilis quidem aut qui cumque omnis nulla.
Fuga tempore aliquam voluptas voluptatem eius consequatur.
Consequatur tenetur praesentium fugiat rem inventore ut.
Ea possimus et blanditiis non possimus commodi accusamus nam.
Sequi accusamus quo.
Id magni placeat nobis et.
Natus ipsum nisi id.", OwnerId = 90, ProjectName = "ashly.biz" },
                        new { Id = 3, Description = @"Debitis id qui explicabo quaerat consequatur rerum.
Reprehenderit dolorum et enim iure aut ut veritatis eos.
Atque aliquid sit vitae temporibus vel ut nostrum consectetur esse.
Natus voluptas error rerum ipsam.
Ut similique est qui sapiente distinctio ad ea veritatis.
Aut ipsum quasi odit ut facere.
Impedit quasi eius autem.
Est placeat ut dolor non omnis eum omnis corporis consequatur.
Ipsam necessitatibus dolores.
Odio occaecati est illo quisquam.
Iusto laudantium quia sed nemo voluptas aut est.", OwnerId = 86, ProjectName = "sedrick.com" },
                        new { Id = 4, Description = @"Quibusdam voluptatem atque repellendus magni est.
Veniam architecto sint aspernatur facere eius quae.
Possimus amet vel neque quasi modi.
Quis pariatur inventore modi temporibus.
Magni ducimus quos.
Quia corrupti optio laboriosam tenetur id iste sit consectetur odio.
Hic accusantium consequatur dicta porro.
Necessitatibus nam dolores recusandae et dolor.
Id quidem qui voluptates itaque molestias.
Fuga voluptatem sed et.
Ut ab aut qui qui fugiat debitis dolor.
Suscipit dolorem est dolores quasi id et repellendus asperiores quae.
Nemo ut id ipsam aut est.
Soluta quis id molestiae et itaque.
Quis consequatur dicta numquam cum.
Ipsa in quos.
Vel eaque est et ut repudiandae.
Doloremque architecto aperiam nihil aut ducimus corrupti dignissimos ipsum.
Velit dolores ut velit sint facere.
Optio labore sequi similique voluptatem rerum ex voluptates maxime.", OwnerId = 21, ProjectName = "joana.org" },
                        new { Id = 5, Description = @"Omnis autem eveniet eveniet eum et recusandae.
Et animi est quas nam.
Et aliquam doloribus saepe quis asperiores ipsum nam possimus.
Impedit magni cum excepturi consequatur.
Voluptatibus rem exercitationem et.
Sed suscipit sint sunt pariatur nulla.
Voluptatem iste quibusdam illum minima molestias.
Corrupti non est.
Debitis ea fugit dolorum et amet optio tempora.
Saepe cum et ullam quia possimus.
Repellendus et voluptatum et iusto voluptatem.
Ut velit rem saepe pariatur ipsum molestias debitis.
Quis temporibus esse.
Corporis et nihil voluptas reprehenderit fuga molestiae.
Rerum earum et est cupiditate vitae eius.
Id consequatur magnam qui fuga assumenda nihil.
Exercitationem pariatur inventore voluptates.
Rerum et excepturi.
Quia quia quis numquam ratione voluptate vel quisquam consectetur.", OwnerId = 71, ProjectName = "deshaun.org" },
                        new { Id = 6, Description = @"Sunt quis enim ullam error.
Nobis et sed beatae unde aperiam perspiciatis.
Occaecati non repellat optio maiores illum ipsam.
Recusandae aliquid officia in iusto aut iusto veritatis dolorem sit.
Cupiditate delectus dolorum.
Nisi cum aut odit quis qui non libero.
Eos et velit.
Nihil natus maiores totam aut magni ex sapiente.
Dolorem aut cum atque voluptatum voluptates consequatur accusantium.", OwnerId = 3, ProjectName = "lawson.org" },
                        new { Id = 7, Description = @"Sit perferendis quo doloremque quis est soluta voluptatum.
Consectetur consequatur omnis ex est adipisci ut.
Quo ut id quidem excepturi officiis molestiae.
Aut ullam ullam sunt voluptas facilis ullam eum ab.
Aut possimus reiciendis omnis harum veniam incidunt.
Voluptates et impedit sed corporis ipsum atque molestias.
Quidem sunt sit molestias eos veniam incidunt voluptatem molestiae.
Iure optio unde excepturi rerum nemo.
Modi repellendus sed.
Harum blanditiis ea.
Sapiente error sunt doloribus asperiores magni id sit aut nam.
Doloremque doloremque fugiat rem maxime dolores sed ut.
Itaque ea aliquid omnis vel ut hic optio aut.
Alias harum et et quia porro eos enim.
Magnam dolor commodi libero nulla quia.
Eaque iure ipsam temporibus culpa.
Iste natus rerum id non sit.
Possimus sit et ex.", OwnerId = 20, ProjectName = "mallie.com" },
                        new { Id = 8, Description = @"Expedita facere est modi est est.
Sunt eligendi molestias.
Ut velit natus eum amet odit sunt.
Illo nobis sunt.
Consequatur aspernatur tempore et debitis aut voluptatum.
Aut eos harum qui.
Sit ex expedita et et autem voluptates.
Dolor quidem natus dolorum occaecati ipsum dicta explicabo.
Commodi quisquam dicta.
Et consequuntur aspernatur culpa.
Natus eius voluptas ducimus.", OwnerId = 68, ProjectName = "kennedy.net" },
                        new { Id = 9, Description = @"Placeat repudiandae ipsum.
Nemo nam et accusantium praesentium fugit dignissimos.
Voluptas iure dicta architecto dolores.
Facilis enim vel tempora iste quia ipsam vel est vel.
A asperiores autem optio dolorem.
Dolor vero consequatur velit quam.
Est libero maiores eos eum quisquam.
Labore autem sit et amet sint fuga occaecati ea.
Labore dolores aut quam optio et sed et distinctio.
Ab et eius est et modi eos est.
Similique amet atque sunt vero eos a.
Laboriosam id dolor ut vel qui perferendis sunt repudiandae.
Accusantium architecto dolorem accusamus atque ipsum.
Dolor sit nesciunt.
Sequi sapiente et perferendis sapiente temporibus.
Facere ea fugit veniam quod est omnis quae.
Dolores labore dicta sed sed qui.
Quo sed reprehenderit cumque nihil ipsam quae beatae aut.", OwnerId = 80, ProjectName = "easter.biz" },
                        new { Id = 10, Description = @"Non at doloremque ex illum excepturi suscipit.
Sit dignissimos sunt iusto eligendi repudiandae perspiciatis dolore.
Autem similique amet illum deleniti similique sunt tenetur odio ea.
Voluptatum earum odio.
Ea hic id eum illo pariatur ullam.
Dignissimos sunt sed.
Est ut fuga dolores sed natus nulla et et praesentium.
Ab veniam earum ea vel sequi ullam enim.
Alias dolores aperiam quod nemo nesciunt.
Odit beatae dolores maxime.
Ad dolorum deleniti nobis illum tempora et repudiandae.
Sed reiciendis rerum.
Iste aspernatur aut ducimus.
Et qui qui vel rerum aut ut aut dolorem autem.
Quod eum sed porro maiores.", OwnerId = 78, ProjectName = "mallie.info" },
                        new { Id = 11, Description = @"Molestiae quibusdam ex nostrum totam occaecati sunt.
Facere inventore beatae expedita nesciunt in animi.
Laudantium tempore consequatur qui recusandae in consequuntur unde ex impedit.
Tempora magnam dolor iusto et qui ex asperiores ut.
Occaecati deleniti officia qui autem quasi.
Quis vitae libero perspiciatis fugit.
Enim doloribus explicabo.
Et cupiditate libero consequatur itaque.
Nam eos aliquam ut fuga molestiae non aut culpa.
Odio earum adipisci omnis enim.
Voluptas vel quaerat ad eaque enim fugit.
Rem dignissimos natus totam.
Totam cum expedita qui quisquam molestiae veniam quia.
Est vero sequi.
Sapiente eos facilis consequatur quibusdam ipsam tenetur quasi adipisci.
Unde distinctio est aliquid placeat sunt dolores sit accusamus.", OwnerId = 47, ProjectName = "ariel.com" },
                        new { Id = 12, Description = @"Ex voluptatum at accusantium iusto tempora quia in sed.
Aliquid magnam occaecati odit.
Et excepturi et enim illum aut et repellat.
Sed aperiam id molestias maiores est temporibus.
Quis et aut quia praesentium molestiae quidem ut id.
Ut omnis alias dolores.
Reprehenderit sed et hic molestiae voluptas possimus.
Iusto voluptatum minima quos ea dolorum et esse.
Eum et sapiente expedita explicabo voluptatem.
Officia sit ullam vitae sapiente vel dignissimos sunt eaque.
Numquam ut ea quod commodi consequatur.
Consectetur in nulla sit et incidunt aliquid.
Minus aut ipsum.
Sed voluptates exercitationem eius voluptas commodi.", OwnerId = 41, ProjectName = "kamryn.net" },
                        new { Id = 13, Description = @"Aperiam nihil blanditiis.
Voluptate est illo est sit dolores molestiae laudantium occaecati rem.
Sequi temporibus hic sapiente tempora enim ad.
Et iste sint.
Sint autem tenetur laudantium eos deleniti cupiditate vel voluptatum.
Nostrum rerum rem cum nihil voluptatem consequatur odit dignissimos omnis.
Et non dolorum officia impedit atque repellendus omnis.
A eum corrupti saepe sed enim et doloremque.
Maiores asperiores distinctio consequuntur dolor dolores consequatur.
Unde nulla quia et reprehenderit aut.
Consequatur ad dolorem suscipit.
Voluptatem repellat quod illo nulla sit et blanditiis in qui.
Dicta reiciendis ut.
Repellendus vitae sed aperiam quia qui.
Recusandae itaque quidem error.
Ad ut necessitatibus voluptatem ratione qui sequi.", OwnerId = 42, ProjectName = "xander.biz" },
                        new { Id = 14, Description = @"Nesciunt officia unde voluptates voluptate.
Eaque sunt pariatur est ex molestiae nesciunt dolores.
Nostrum non veritatis aut.
Minima blanditiis harum odit est debitis.
Ex dolorem quia rem non voluptatum quo officiis provident aperiam.
Cupiditate sed animi rem quo.
Asperiores sapiente aut aut sint eos corrupti.
Qui adipisci alias cumque a dignissimos eius non assumenda soluta.
Qui dolor eum qui quia.
Soluta quaerat dolorum ut animi.
Aut quod aut fugit qui omnis a quo sapiente.
Unde beatae minima quo ipsum in deserunt sunt.
Et sint quia maiores ducimus dolorem excepturi dolor placeat quo.
Et eum pariatur vel adipisci sapiente hic.", OwnerId = 33, ProjectName = "jeramie.net" },
                        new { Id = 15, Description = @"Corporis sunt et placeat ipsum atque dicta aut libero.
Ut ipsum saepe animi facere natus hic.
Asperiores quia repellat ea.
Neque tempora ut rerum non et ut mollitia et.
Architecto ut eveniet qui esse laboriosam exercitationem.
Minus recusandae suscipit nulla cum atque deserunt quia.
Autem ad omnis est nulla rerum.
Laudantium cupiditate enim nulla debitis.
In recusandae ullam omnis illum cumque.
Quod sed debitis optio perspiciatis voluptatem nihil iusto voluptatem.
Esse quae alias labore necessitatibus voluptatem atque.
Incidunt tenetur culpa.
Saepe quasi qui repellendus quaerat.
In perspiciatis consequuntur nam saepe aliquid facilis.
In veritatis veritatis culpa occaecati aut qui aut vero.
Debitis labore molestias et illum perspiciatis officia maxime ad.
Facilis aut et omnis consequatur necessitatibus.
Omnis nihil placeat.", OwnerId = 16, ProjectName = "lyla.name" },
                        new { Id = 16, Description = @"Quam rerum et iusto optio numquam sint numquam expedita et.
Accusantium repellendus qui.
Beatae voluptatem architecto quaerat adipisci deserunt qui.
Sunt harum nulla consequatur unde.
Rerum tempora rerum.", OwnerId = 46, ProjectName = "matteo.info" },
                        new { Id = 17, Description = @"Nemo culpa ipsum est deserunt qui at maiores et magnam.
Voluptas tempore alias.
Suscipit eos voluptas mollitia facilis beatae aut.
Pariatur quis odit perferendis soluta vel similique sunt sit.
Qui voluptas dolores sunt totam alias ut qui qui assumenda.
Voluptatem impedit iusto quidem expedita nemo mollitia.
Quibusdam hic vero quas est.
Ex atque similique quia est.
Neque quo at non neque.
Dolore reprehenderit voluptas.
Adipisci dolores eaque voluptatem non.
Tempore autem voluptatem quasi aut est sed eaque.
Suscipit est voluptas fugit sint.
Minima reiciendis rem molestiae id vero et voluptatum.", OwnerId = 59, ProjectName = "andy.biz" },
                        new { Id = 18, Description = @"Possimus commodi totam praesentium autem eligendi.
Adipisci voluptatem sed voluptatem odio dolor illum et dolorem.
Deleniti ad consequatur optio sint.
Error quo molestiae aut voluptas ut dignissimos.
Assumenda soluta aspernatur.", OwnerId = 29, ProjectName = "thurman.org" },
                        new { Id = 19, Description = @"Nihil nihil rem consequuntur dignissimos sequi doloribus molestiae eaque nam.
Minima culpa non ut id voluptas nulla et.
Accusamus rerum quae nostrum impedit cupiditate omnis.
Vitae sed voluptatem sapiente maiores molestias at aut tempora.
Architecto velit nulla et voluptas aut magnam neque et.
Ducimus commodi odio beatae sapiente eligendi odit sed distinctio.
Quam sint animi ut.
Quas ut est exercitationem architecto.
Magni excepturi ab.
Dolores omnis quis sed earum ipsa perspiciatis explicabo quo.", OwnerId = 31, ProjectName = "milford.com" },
                        new { Id = 20, Description = @"Exercitationem in ipsam odio quae consequatur sequi consequatur laborum sequi.
Possimus natus et ea omnis.
Pariatur reprehenderit nemo laudantium repudiandae.
Quam quisquam eos debitis dolorem necessitatibus molestiae et.
Odit est alias tempore omnis eligendi.
Soluta et nobis dolorem numquam vero.
Deleniti soluta minus hic.
Accusamus nihil recusandae sed vel nam eveniet quisquam et quos.", OwnerId = 34, ProjectName = "thea.net" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProjectId");

                    b.Property<int>("Rating");

                    b.Property<int>("SkillId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectRequirments");

                    b.HasData(
                        new { Id = 1, Rating = 5, SkillId = 16 },
                        new { Id = 2, Rating = 5, SkillId = 17 },
                        new { Id = 3, Rating = 2, SkillId = 17 },
                        new { Id = 4, Rating = 4, SkillId = 18 },
                        new { Id = 5, Rating = 3, SkillId = 13 },
                        new { Id = 6, Rating = 1, SkillId = 23 },
                        new { Id = 7, Rating = 4, SkillId = 17 },
                        new { Id = 8, Rating = 1, SkillId = 21 },
                        new { Id = 9, Rating = 3, SkillId = 5 },
                        new { Id = 10, Rating = 3, SkillId = 17 },
                        new { Id = 11, Rating = 4, SkillId = 20 },
                        new { Id = 12, Rating = 2, SkillId = 12 },
                        new { Id = 13, Rating = 2, SkillId = 19 },
                        new { Id = 14, Rating = 1, SkillId = 9 },
                        new { Id = 15, Rating = 2, SkillId = 6 },
                        new { Id = 16, Rating = 4, SkillId = 19 },
                        new { Id = 17, Rating = 4, SkillId = 6 },
                        new { Id = 18, Rating = 1, SkillId = 16 },
                        new { Id = 19, Rating = 3, SkillId = 10 },
                        new { Id = 20, Rating = 5, SkillId = 14 },
                        new { Id = 21, Rating = 1, SkillId = 10 },
                        new { Id = 22, Rating = 3, SkillId = 7 },
                        new { Id = 23, Rating = 5, SkillId = 10 },
                        new { Id = 24, Rating = 5, SkillId = 13 },
                        new { Id = 25, Rating = 2, SkillId = 22 },
                        new { Id = 26, Rating = 4, SkillId = 23 },
                        new { Id = 27, Rating = 1, SkillId = 22 },
                        new { Id = 28, Rating = 2, SkillId = 20 },
                        new { Id = 29, Rating = 4, SkillId = 12 },
                        new { Id = 30, Rating = 4, SkillId = 9 },
                        new { Id = 31, Rating = 1, SkillId = 5 },
                        new { Id = 32, Rating = 1, SkillId = 24 },
                        new { Id = 33, Rating = 3, SkillId = 13 },
                        new { Id = 34, Rating = 5, SkillId = 15 },
                        new { Id = 35, Rating = 3, SkillId = 15 },
                        new { Id = 36, Rating = 3, SkillId = 22 },
                        new { Id = 37, Rating = 5, SkillId = 4 },
                        new { Id = 38, Rating = 4, SkillId = 5 },
                        new { Id = 39, Rating = 4, SkillId = 6 },
                        new { Id = 40, Rating = 4, SkillId = 14 },
                        new { Id = 41, Rating = 3, SkillId = 3 },
                        new { Id = 42, Rating = 5, SkillId = 19 },
                        new { Id = 43, Rating = 3, SkillId = 13 },
                        new { Id = 44, Rating = 2, SkillId = 14 },
                        new { Id = 45, Rating = 1, SkillId = 21 },
                        new { Id = 46, Rating = 3, SkillId = 21 }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SkillName");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new { Id = 1, SkillName = "C#" },
                        new { Id = 2, SkillName = "Haskel" },
                        new { Id = 3, SkillName = "Swift" },
                        new { Id = 4, SkillName = "Java" },
                        new { Id = 5, SkillName = "R" },
                        new { Id = 6, SkillName = "PHP" },
                        new { Id = 7, SkillName = "Assembly" },
                        new { Id = 8, SkillName = "Go" },
                        new { Id = 9, SkillName = "Ruby" },
                        new { Id = 10, SkillName = "Perl" },
                        new { Id = 11, SkillName = "MS-SQL" },
                        new { Id = 12, SkillName = "JavaScript" },
                        new { Id = 13, SkillName = "TypeScript" },
                        new { Id = 14, SkillName = "C" },
                        new { Id = 15, SkillName = "C++" },
                        new { Id = 16, SkillName = "Python" },
                        new { Id = 17, SkillName = "PL/SQL" },
                        new { Id = 18, SkillName = "MongoDb" },
                        new { Id = 19, SkillName = "Lisp" },
                        new { Id = 20, SkillName = "Prolog" },
                        new { Id = 21, SkillName = "D" },
                        new { Id = 22, SkillName = "Rust" },
                        new { Id = 23, SkillName = "Android" },
                        new { Id = 24, SkillName = ".Net" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<int>("GitHubId");

                    b.Property<string>("Login");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, GitHubId = 0, Login = "Andre.Hilll45" },
                        new { Id = 2, GitHubId = 0, Login = "Wilburn27" },
                        new { Id = 3, GitHubId = 0, Login = "Enrique.Considine" },
                        new { Id = 4, GitHubId = 0, Login = "Erich.Lueilwitz" },
                        new { Id = 5, GitHubId = 0, Login = "Sigrid93" },
                        new { Id = 6, GitHubId = 0, Login = "Allene26" },
                        new { Id = 7, GitHubId = 0, Login = "Sunny_Nader" },
                        new { Id = 8, GitHubId = 0, Login = "Ignacio11" },
                        new { Id = 9, GitHubId = 0, Login = "Pascale.Windler" },
                        new { Id = 10, GitHubId = 0, Login = "Clarissa6" },
                        new { Id = 11, GitHubId = 0, Login = "Brenden.Lockman" },
                        new { Id = 12, GitHubId = 0, Login = "Rahul_Jacobi82" },
                        new { Id = 13, GitHubId = 0, Login = "Izaiah89" },
                        new { Id = 14, GitHubId = 0, Login = "Rosa_Armstrong" },
                        new { Id = 15, GitHubId = 0, Login = "Remington_Lowe" },
                        new { Id = 16, GitHubId = 0, Login = "Jeanne.Sipes48" },
                        new { Id = 17, GitHubId = 0, Login = "Kaya.Hickle96" },
                        new { Id = 18, GitHubId = 0, Login = "Dorris79" },
                        new { Id = 19, GitHubId = 0, Login = "Jermey.Beatty50" },
                        new { Id = 20, GitHubId = 0, Login = "Phyllis_Koch31" },
                        new { Id = 21, GitHubId = 0, Login = "Monica_Emard98" },
                        new { Id = 22, GitHubId = 0, Login = "Marielle97" },
                        new { Id = 23, GitHubId = 0, Login = "Else_Oberbrunner17" },
                        new { Id = 24, GitHubId = 0, Login = "Enos.Spinka" },
                        new { Id = 25, GitHubId = 0, Login = "Nolan_Kuhic74" },
                        new { Id = 26, GitHubId = 0, Login = "Althea_Lebsack" },
                        new { Id = 27, GitHubId = 0, Login = "Frederique.Bauch" },
                        new { Id = 28, GitHubId = 0, Login = "Louie.Sporer" },
                        new { Id = 29, GitHubId = 0, Login = "Donna_Mohr" },
                        new { Id = 30, GitHubId = 0, Login = "Gennaro58" },
                        new { Id = 31, GitHubId = 0, Login = "Rosetta.Crist58" },
                        new { Id = 32, GitHubId = 0, Login = "Brenna40" },
                        new { Id = 33, GitHubId = 0, Login = "Ashly.Kuvalis" },
                        new { Id = 34, GitHubId = 0, Login = "Jaquan.Turcotte" },
                        new { Id = 35, GitHubId = 0, Login = "Oceane42" },
                        new { Id = 36, GitHubId = 0, Login = "Adolf.Adams75" },
                        new { Id = 37, GitHubId = 0, Login = "America11" },
                        new { Id = 38, GitHubId = 0, Login = "Georgianna.Torp89" },
                        new { Id = 39, GitHubId = 0, Login = "Sidney.Robel" },
                        new { Id = 40, GitHubId = 0, Login = "Darrin89" },
                        new { Id = 41, GitHubId = 0, Login = "Katelynn40" },
                        new { Id = 42, GitHubId = 0, Login = "Pietro_Quigley61" },
                        new { Id = 43, GitHubId = 0, Login = "Lavon83" },
                        new { Id = 44, GitHubId = 0, Login = "Cade_Vandervort8" },
                        new { Id = 45, GitHubId = 0, Login = "Hildegard70" },
                        new { Id = 46, GitHubId = 0, Login = "Lexus_Morar1" },
                        new { Id = 47, GitHubId = 0, Login = "Marjolaine_Weissnat" },
                        new { Id = 48, GitHubId = 0, Login = "Lura45" },
                        new { Id = 49, GitHubId = 0, Login = "Julius.Hane" },
                        new { Id = 50, GitHubId = 0, Login = "Julie_Beer" },
                        new { Id = 51, GitHubId = 0, Login = "Edmond.Maggio74" },
                        new { Id = 52, GitHubId = 0, Login = "Richmond.Predovic" },
                        new { Id = 53, GitHubId = 0, Login = "Uriel_Wiegand" },
                        new { Id = 54, GitHubId = 0, Login = "Modesta.Kuhic" },
                        new { Id = 55, GitHubId = 0, Login = "Maureen.Hahn" },
                        new { Id = 56, GitHubId = 0, Login = "Rita_Leuschke68" },
                        new { Id = 57, GitHubId = 0, Login = "Georgianna_Johns" },
                        new { Id = 58, GitHubId = 0, Login = "Stephen_Effertz33" },
                        new { Id = 59, GitHubId = 0, Login = "Amaya.Tremblay" },
                        new { Id = 60, GitHubId = 0, Login = "Royal_Frami69" },
                        new { Id = 61, GitHubId = 0, Login = "Deshaun_Lang" },
                        new { Id = 62, GitHubId = 0, Login = "Rollin83" },
                        new { Id = 63, GitHubId = 0, Login = "Nayeli.West" },
                        new { Id = 64, GitHubId = 0, Login = "Aleen.Balistreri" },
                        new { Id = 65, GitHubId = 0, Login = "Isai32" },
                        new { Id = 66, GitHubId = 0, Login = "Alysa_Rippin39" },
                        new { Id = 67, GitHubId = 0, Login = "Howard.Nikolaus45" },
                        new { Id = 68, GitHubId = 0, Login = "Gail83" },
                        new { Id = 69, GitHubId = 0, Login = "Maude57" },
                        new { Id = 70, GitHubId = 0, Login = "Kim.Ondricka46" },
                        new { Id = 71, GitHubId = 0, Login = "Orie.Harvey86" },
                        new { Id = 72, GitHubId = 0, Login = "Christopher_Effertz" },
                        new { Id = 73, GitHubId = 0, Login = "Trycia_Graham" },
                        new { Id = 74, GitHubId = 0, Login = "Lily.Quitzon" },
                        new { Id = 75, GitHubId = 0, Login = "Chaz.Hayes" },
                        new { Id = 76, GitHubId = 0, Login = "Kiarra18" },
                        new { Id = 77, GitHubId = 0, Login = "Esteban_Champlin70" },
                        new { Id = 78, GitHubId = 0, Login = "Fatima.Leuschke10" },
                        new { Id = 79, GitHubId = 0, Login = "Kiarra_Larkin" },
                        new { Id = 80, GitHubId = 0, Login = "Johathan41" },
                        new { Id = 81, GitHubId = 0, Login = "Dorian17" },
                        new { Id = 82, GitHubId = 0, Login = "Kyra17" },
                        new { Id = 83, GitHubId = 0, Login = "Jayne.Kling" },
                        new { Id = 84, GitHubId = 0, Login = "Conner_White" },
                        new { Id = 85, GitHubId = 0, Login = "Kaela53" },
                        new { Id = 86, GitHubId = 0, Login = "Denis_Medhurst24" },
                        new { Id = 87, GitHubId = 0, Login = "Jonas_Collins40" },
                        new { Id = 88, GitHubId = 0, Login = "Ricardo16" },
                        new { Id = 89, GitHubId = 0, Login = "Bertram.Grimes54" },
                        new { Id = 90, GitHubId = 0, Login = "Linwood_Prosacco" },
                        new { Id = 91, GitHubId = 0, Login = "Arne90" },
                        new { Id = 92, GitHubId = 0, Login = "Linwood.Strosin" },
                        new { Id = 93, GitHubId = 0, Login = "Ivy.Zboncak" },
                        new { Id = 94, GitHubId = 0, Login = "Marilie_Dickens" },
                        new { Id = 95, GitHubId = 0, Login = "Ara17" },
                        new { Id = 96, GitHubId = 0, Login = "Archibald_Muller" },
                        new { Id = 97, GitHubId = 0, Login = "Allison_Smith" },
                        new { Id = 98, GitHubId = 0, Login = "Gene_Larson" },
                        new { Id = 99, GitHubId = 0, Login = "Michael.Rempel15" },
                        new { Id = 100, GitHubId = 0, Login = "Lenny41" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserFollowers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FollowerId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.ToTable("UserFollowers");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Rating");

                    b.Property<int>("SkillId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");

                    b.HasData(
                        new { Id = 1, Rating = 2, SkillId = 6, UserId = 1 },
                        new { Id = 2, Rating = 0, SkillId = 11, UserId = 1 },
                        new { Id = 3, Rating = 1, SkillId = 12, UserId = 2 },
                        new { Id = 4, Rating = 2, SkillId = 10, UserId = 2 },
                        new { Id = 5, Rating = 2, SkillId = 21, UserId = 2 },
                        new { Id = 6, Rating = 4, SkillId = 13, UserId = 3 },
                        new { Id = 7, Rating = 5, SkillId = 24, UserId = 3 },
                        new { Id = 8, Rating = 2, SkillId = 24, UserId = 4 },
                        new { Id = 9, Rating = 0, SkillId = 20, UserId = 4 },
                        new { Id = 10, Rating = 1, SkillId = 19, UserId = 5 },
                        new { Id = 11, Rating = 1, SkillId = 7, UserId = 5 },
                        new { Id = 12, Rating = 1, SkillId = 9, UserId = 7 },
                        new { Id = 13, Rating = 2, SkillId = 9, UserId = 9 },
                        new { Id = 14, Rating = 1, SkillId = 14, UserId = 9 },
                        new { Id = 15, Rating = 4, SkillId = 13, UserId = 10 },
                        new { Id = 16, Rating = 1, SkillId = 12, UserId = 10 },
                        new { Id = 17, Rating = 0, SkillId = 14, UserId = 10 },
                        new { Id = 18, Rating = 1, SkillId = 12, UserId = 11 },
                        new { Id = 19, Rating = 4, SkillId = 5, UserId = 11 },
                        new { Id = 20, Rating = 5, SkillId = 6, UserId = 11 },
                        new { Id = 21, Rating = 4, SkillId = 10, UserId = 12 },
                        new { Id = 22, Rating = 4, SkillId = 23, UserId = 13 },
                        new { Id = 23, Rating = 0, SkillId = 1, UserId = 14 },
                        new { Id = 24, Rating = 4, SkillId = 19, UserId = 15 },
                        new { Id = 25, Rating = 4, SkillId = 2, UserId = 15 },
                        new { Id = 26, Rating = 4, SkillId = 12, UserId = 15 },
                        new { Id = 27, Rating = 5, SkillId = 17, UserId = 16 },
                        new { Id = 28, Rating = 0, SkillId = 13, UserId = 17 },
                        new { Id = 29, Rating = 0, SkillId = 25, UserId = 18 },
                        new { Id = 30, Rating = 0, SkillId = 24, UserId = 18 },
                        new { Id = 31, Rating = 1, SkillId = 16, UserId = 19 },
                        new { Id = 32, Rating = 3, SkillId = 19, UserId = 19 },
                        new { Id = 33, Rating = 1, SkillId = 18, UserId = 20 },
                        new { Id = 34, Rating = 1, SkillId = 18, UserId = 20 },
                        new { Id = 35, Rating = 1, SkillId = 11, UserId = 21 },
                        new { Id = 36, Rating = 2, SkillId = 12, UserId = 22 },
                        new { Id = 37, Rating = 2, SkillId = 1, UserId = 22 },
                        new { Id = 38, Rating = 4, SkillId = 2, UserId = 22 },
                        new { Id = 39, Rating = 1, SkillId = 17, UserId = 23 },
                        new { Id = 40, Rating = 4, SkillId = 17, UserId = 23 },
                        new { Id = 41, Rating = 4, SkillId = 25, UserId = 23 },
                        new { Id = 42, Rating = 2, SkillId = 1, UserId = 24 },
                        new { Id = 43, Rating = 2, SkillId = 9, UserId = 24 },
                        new { Id = 44, Rating = 4, SkillId = 20, UserId = 25 },
                        new { Id = 45, Rating = 3, SkillId = 22, UserId = 26 },
                        new { Id = 46, Rating = 3, SkillId = 22, UserId = 26 },
                        new { Id = 47, Rating = 5, SkillId = 15, UserId = 26 },
                        new { Id = 48, Rating = 5, SkillId = 17, UserId = 26 },
                        new { Id = 49, Rating = 5, SkillId = 1, UserId = 27 },
                        new { Id = 50, Rating = 0, SkillId = 24, UserId = 28 },
                        new { Id = 51, Rating = 1, SkillId = 5, UserId = 28 },
                        new { Id = 52, Rating = 1, SkillId = 1, UserId = 29 },
                        new { Id = 53, Rating = 0, SkillId = 22, UserId = 31 },
                        new { Id = 54, Rating = 4, SkillId = 21, UserId = 33 },
                        new { Id = 55, Rating = 4, SkillId = 23, UserId = 34 },
                        new { Id = 56, Rating = 2, SkillId = 13, UserId = 34 },
                        new { Id = 57, Rating = 4, SkillId = 23, UserId = 34 },
                        new { Id = 58, Rating = 2, SkillId = 8, UserId = 34 },
                        new { Id = 59, Rating = 1, SkillId = 21, UserId = 34 },
                        new { Id = 60, Rating = 2, SkillId = 11, UserId = 35 },
                        new { Id = 61, Rating = 1, SkillId = 7, UserId = 35 },
                        new { Id = 62, Rating = 2, SkillId = 23, UserId = 35 },
                        new { Id = 63, Rating = 0, SkillId = 10, UserId = 36 },
                        new { Id = 64, Rating = 1, SkillId = 6, UserId = 37 },
                        new { Id = 65, Rating = 1, SkillId = 6, UserId = 37 },
                        new { Id = 66, Rating = 5, SkillId = 17, UserId = 38 },
                        new { Id = 67, Rating = 2, SkillId = 11, UserId = 38 },
                        new { Id = 68, Rating = 4, SkillId = 1, UserId = 39 },
                        new { Id = 69, Rating = 0, SkillId = 11, UserId = 39 },
                        new { Id = 70, Rating = 4, SkillId = 8, UserId = 39 },
                        new { Id = 71, Rating = 5, SkillId = 14, UserId = 41 },
                        new { Id = 72, Rating = 4, SkillId = 22, UserId = 41 },
                        new { Id = 73, Rating = 2, SkillId = 23, UserId = 41 },
                        new { Id = 74, Rating = 0, SkillId = 7, UserId = 42 },
                        new { Id = 75, Rating = 4, SkillId = 15, UserId = 43 },
                        new { Id = 76, Rating = 4, SkillId = 7, UserId = 43 },
                        new { Id = 77, Rating = 5, SkillId = 19, UserId = 43 },
                        new { Id = 78, Rating = 3, SkillId = 23, UserId = 44 },
                        new { Id = 79, Rating = 2, SkillId = 15, UserId = 45 },
                        new { Id = 80, Rating = 0, SkillId = 17, UserId = 45 },
                        new { Id = 81, Rating = 3, SkillId = 25, UserId = 46 },
                        new { Id = 82, Rating = 3, SkillId = 1, UserId = 47 },
                        new { Id = 83, Rating = 2, SkillId = 16, UserId = 47 },
                        new { Id = 84, Rating = 4, SkillId = 18, UserId = 47 },
                        new { Id = 85, Rating = 0, SkillId = 5, UserId = 48 },
                        new { Id = 86, Rating = 5, SkillId = 10, UserId = 48 },
                        new { Id = 87, Rating = 5, SkillId = 19, UserId = 49 },
                        new { Id = 88, Rating = 4, SkillId = 12, UserId = 50 },
                        new { Id = 89, Rating = 5, SkillId = 7, UserId = 50 },
                        new { Id = 90, Rating = 4, SkillId = 8, UserId = 51 },
                        new { Id = 91, Rating = 2, SkillId = 25, UserId = 52 },
                        new { Id = 92, Rating = 4, SkillId = 8, UserId = 52 },
                        new { Id = 93, Rating = 3, SkillId = 22, UserId = 53 },
                        new { Id = 94, Rating = 2, SkillId = 9, UserId = 54 },
                        new { Id = 95, Rating = 2, SkillId = 2, UserId = 54 },
                        new { Id = 96, Rating = 0, SkillId = 14, UserId = 55 },
                        new { Id = 97, Rating = 5, SkillId = 22, UserId = 56 },
                        new { Id = 98, Rating = 0, SkillId = 13, UserId = 56 },
                        new { Id = 99, Rating = 0, SkillId = 25, UserId = 57 },
                        new { Id = 100, Rating = 2, SkillId = 20, UserId = 58 },
                        new { Id = 101, Rating = 1, SkillId = 17, UserId = 58 },
                        new { Id = 102, Rating = 5, SkillId = 25, UserId = 58 },
                        new { Id = 103, Rating = 4, SkillId = 4, UserId = 59 },
                        new { Id = 104, Rating = 5, SkillId = 1, UserId = 61 },
                        new { Id = 105, Rating = 1, SkillId = 20, UserId = 62 },
                        new { Id = 106, Rating = 2, SkillId = 4, UserId = 62 },
                        new { Id = 107, Rating = 0, SkillId = 7, UserId = 62 },
                        new { Id = 108, Rating = 3, SkillId = 1, UserId = 62 },
                        new { Id = 109, Rating = 2, SkillId = 3, UserId = 63 },
                        new { Id = 110, Rating = 3, SkillId = 23, UserId = 63 },
                        new { Id = 111, Rating = 3, SkillId = 11, UserId = 63 },
                        new { Id = 112, Rating = 0, SkillId = 16, UserId = 64 },
                        new { Id = 113, Rating = 3, SkillId = 23, UserId = 65 },
                        new { Id = 114, Rating = 3, SkillId = 14, UserId = 65 },
                        new { Id = 115, Rating = 2, SkillId = 23, UserId = 65 },
                        new { Id = 116, Rating = 2, SkillId = 12, UserId = 67 },
                        new { Id = 117, Rating = 3, SkillId = 6, UserId = 67 },
                        new { Id = 118, Rating = 3, SkillId = 18, UserId = 69 },
                        new { Id = 119, Rating = 1, SkillId = 25, UserId = 69 },
                        new { Id = 120, Rating = 1, SkillId = 18, UserId = 69 },
                        new { Id = 121, Rating = 1, SkillId = 22, UserId = 71 },
                        new { Id = 122, Rating = 2, SkillId = 21, UserId = 73 },
                        new { Id = 123, Rating = 5, SkillId = 18, UserId = 74 },
                        new { Id = 124, Rating = 3, SkillId = 21, UserId = 74 },
                        new { Id = 125, Rating = 1, SkillId = 3, UserId = 75 },
                        new { Id = 126, Rating = 5, SkillId = 6, UserId = 75 },
                        new { Id = 127, Rating = 5, SkillId = 14, UserId = 75 },
                        new { Id = 128, Rating = 3, SkillId = 24, UserId = 76 },
                        new { Id = 129, Rating = 1, SkillId = 4, UserId = 76 },
                        new { Id = 130, Rating = 1, SkillId = 21, UserId = 77 },
                        new { Id = 131, Rating = 1, SkillId = 9, UserId = 77 },
                        new { Id = 132, Rating = 0, SkillId = 10, UserId = 77 },
                        new { Id = 133, Rating = 4, SkillId = 21, UserId = 78 },
                        new { Id = 134, Rating = 2, SkillId = 18, UserId = 79 },
                        new { Id = 135, Rating = 5, SkillId = 16, UserId = 79 },
                        new { Id = 136, Rating = 5, SkillId = 9, UserId = 80 },
                        new { Id = 137, Rating = 2, SkillId = 3, UserId = 80 },
                        new { Id = 138, Rating = 5, SkillId = 14, UserId = 81 },
                        new { Id = 139, Rating = 1, SkillId = 20, UserId = 82 },
                        new { Id = 140, Rating = 4, SkillId = 6, UserId = 83 },
                        new { Id = 141, Rating = 1, SkillId = 19, UserId = 83 },
                        new { Id = 142, Rating = 0, SkillId = 6, UserId = 83 },
                        new { Id = 143, Rating = 5, SkillId = 5, UserId = 84 },
                        new { Id = 144, Rating = 1, SkillId = 9, UserId = 85 },
                        new { Id = 145, Rating = 1, SkillId = 13, UserId = 85 },
                        new { Id = 146, Rating = 3, SkillId = 21, UserId = 86 },
                        new { Id = 147, Rating = 2, SkillId = 12, UserId = 87 },
                        new { Id = 148, Rating = 3, SkillId = 2, UserId = 87 },
                        new { Id = 149, Rating = 2, SkillId = 1, UserId = 87 },
                        new { Id = 150, Rating = 0, SkillId = 25, UserId = 88 },
                        new { Id = 151, Rating = 2, SkillId = 19, UserId = 88 },
                        new { Id = 152, Rating = 0, SkillId = 20, UserId = 88 },
                        new { Id = 153, Rating = 1, SkillId = 23, UserId = 88 },
                        new { Id = 154, Rating = 1, SkillId = 22, UserId = 89 },
                        new { Id = 155, Rating = 5, SkillId = 13, UserId = 91 },
                        new { Id = 156, Rating = 4, SkillId = 9, UserId = 92 },
                        new { Id = 157, Rating = 4, SkillId = 3, UserId = 94 },
                        new { Id = 158, Rating = 0, SkillId = 21, UserId = 95 },
                        new { Id = 159, Rating = 0, SkillId = 19, UserId = 97 },
                        new { Id = 160, Rating = 2, SkillId = 11, UserId = 97 },
                        new { Id = 161, Rating = 0, SkillId = 25, UserId = 97 },
                        new { Id = 162, Rating = 0, SkillId = 20, UserId = 97 },
                        new { Id = 163, Rating = 4, SkillId = 10, UserId = 98 },
                        new { Id = 164, Rating = 4, SkillId = 19, UserId = 100 }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectMember", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collaboo.App.WebAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectRequirement", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Project")
                        .WithMany("Requirements")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Collaboo.App.WebAPI.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserFollowers", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Follower", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserSkills", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collaboo.App.WebAPI.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
