// <auto-generated />
using System;
using Collaboo.App.WebAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Collaboo.App.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181118030452_Seed2")]
    partial class Seed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Follower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("GitHubRepoUrl");

                    b.Property<int>("OwnerId");

                    b.Property<string>("ProjectName");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new { Id = 1, Description = @"Est eum sit reiciendis voluptates aut dolorem sequi aut ratione.
Fuga pariatur et et delectus eaque asperiores cumque.
Iusto qui ipsum.
Vel qui excepturi pariatur ut est soluta.
Vitae dolores ad et nesciunt.
Enim est est aut laborum accusantium est aspernatur.
Ipsum numquam et sint sed.
Ullam rem et numquam quo.
Sint exercitationem ipsam sit.
Totam odio ut porro officia.", OwnerId = 71, ProjectName = "ramiro.biz" },
                        new { Id = 2, Description = @"Autem omnis non.
Aut quo sed laboriosam.
Ex quia voluptatum tenetur repellendus distinctio velit impedit.
Culpa facere reprehenderit sit cumque quia.
Ipsum iste natus culpa quas aut modi.
Ipsam et sint expedita quasi nihil.
Qui tenetur soluta dolorem fugit doloribus.
Possimus illo dolor repellat consequatur quo.
Dolorum ipsa pariatur rerum qui quo sequi natus possimus magni.
Hic repellat rerum eos maxime facere rerum.
Consequuntur ea odio et officiis non sunt est.
Quas ea molestias iusto excepturi excepturi eligendi aut et.
Atque accusamus ullam quo adipisci unde ad neque asperiores.
Saepe enim nihil ex harum qui est dolor reprehenderit.
Cum perferendis voluptatem aliquid illo ex fuga fugit odio atque.
Voluptatibus cum maiores sequi accusamus eum occaecati dolore aut mollitia.", OwnerId = 5, ProjectName = "kirsten.org" },
                        new { Id = 3, Description = @"Reiciendis voluptatem aut non.
Excepturi corrupti sunt explicabo rem porro rerum repellendus quo molestiae.
Est molestias ut repudiandae.
Odio sed omnis facere dicta recusandae quis vel.
Iusto enim ducimus vero autem rem nemo excepturi.
Et quos qui necessitatibus soluta voluptatem rerum.
Voluptate dolor iusto quia et earum asperiores natus.
Hic ipsa quia vel culpa sed impedit.
Eaque voluptate et molestiae praesentium blanditiis.
Non non totam quam ab unde occaecati laborum accusamus.
Cupiditate aut rerum ullam consequatur.
Qui ullam quo cupiditate voluptatem.
Voluptas at nostrum debitis nihil.
Quod eum vel rerum est culpa fugit eos.
In molestias doloribus molestiae et corporis.
Illo sunt voluptas dolorem libero eaque.
Fuga fuga non.
Officiis neque et consequuntur quia consequuntur debitis.
Corrupti sed in iure commodi amet incidunt eveniet officiis.", OwnerId = 80, ProjectName = "rosalyn.com" },
                        new { Id = 4, Description = @"Corporis quibusdam sed.
Aliquam reiciendis nihil.
Amet quia autem asperiores labore.
Vero qui suscipit et omnis natus vel molestiae deleniti nihil.
Reiciendis iusto eos ipsum fugiat dolor.
Facere quo eos illum et veritatis accusamus eveniet dolorem.
Aliquid aliquam deserunt quis.
Quaerat ipsa nihil praesentium reiciendis perspiciatis ad modi autem voluptatem.
Impedit ad ut error dolorem ex.
A labore ea aut eaque non enim.
Et reprehenderit libero in modi aut doloremque doloremque dolor aspernatur.
Autem et nostrum deleniti et corrupti et nihil.
Mollitia ea id voluptatibus asperiores.
Quidem dolores unde ratione alias eveniet amet voluptatibus.
Aut iste quibusdam explicabo iure soluta et commodi laudantium quam.
Quod libero possimus temporibus fuga ut aut sint in nostrum.
Nobis culpa excepturi rem saepe atque aperiam explicabo at.
Illum qui mollitia inventore.", OwnerId = 69, ProjectName = "grover.com" },
                        new { Id = 5, Description = @"Repellat eos natus perferendis ut.
Autem omnis occaecati laudantium autem ut culpa animi explicabo accusamus.
Qui sint repellendus omnis.
Quis similique autem et enim.
Qui recusandae eos quasi.
Ab exercitationem et quia.
Perspiciatis quas occaecati est excepturi harum veritatis.
Labore autem quas consectetur rem qui sed rerum officia libero.
Asperiores modi quae optio numquam doloremque officia voluptas quisquam.
Non nemo dignissimos.
Est eaque velit ut aperiam illum id molestias.
Nobis voluptatum expedita sed praesentium voluptatem hic ea praesentium.
Aut magni nisi et consequatur corporis eligendi molestiae.
Laboriosam eveniet impedit corrupti veritatis.
Dolorem dolor nihil dolorum iste at.", OwnerId = 3, ProjectName = "jazmyne.info" },
                        new { Id = 6, Description = @"Natus dolores consequuntur aut.
Distinctio quasi cum natus laborum nemo ut id sapiente.
Saepe et ipsum aut reiciendis.
Mollitia sunt quidem sed dolore quod et est at facilis.
Eos deserunt maxime velit quibusdam exercitationem similique labore rerum consequatur.
Eum sint labore aut expedita numquam a.
Ipsam vel eum incidunt sapiente ea quos.
Cupiditate et neque et impedit ut.
Ea aut eius qui aspernatur.
Animi id laboriosam quia.", OwnerId = 10, ProjectName = "devonte.com" },
                        new { Id = 7, Description = @"Vitae eligendi illum aliquam.
Laborum facere ea dolor quibusdam.
Dolorem quae ipsam voluptatum et.
Eos sed fugiat sunt odio quasi eos praesentium porro.
Quae illo accusamus qui quis ipsum eum quo.
Dicta qui rerum cumque est et.
Ut temporibus enim iste quam eos.
Corporis in sint laudantium ab.
Dolorum tenetur quibusdam laborum aut impedit nemo repudiandae.", OwnerId = 66, ProjectName = "tremayne.name" },
                        new { Id = 8, Description = @"Alias qui nisi modi et amet.
Alias est quasi ratione nesciunt modi.
Repellendus error quod qui.
Suscipit adipisci at dolores et accusantium qui itaque.
Cupiditate eligendi at expedita saepe.
Eos ducimus sapiente dolor esse minima est rerum saepe aut.
Qui placeat non occaecati ut repudiandae atque rerum.
Veniam voluptatem nobis est velit.
Dolore aspernatur deleniti aperiam eius corrupti ut veniam quia.
Id error eaque molestiae est.
A magnam consequatur sunt reiciendis velit qui.
Omnis quis quo error.
Impedit voluptas ad reiciendis rerum doloremque excepturi nesciunt.
Nam nesciunt amet totam quia amet maxime aliquid ducimus.
Animi est adipisci iusto nobis fuga quibusdam.", OwnerId = 84, ProjectName = "dorris.biz" },
                        new { Id = 9, Description = @"Omnis cumque fuga laborum sunt sit qui qui qui.
In aspernatur officia nulla.
Excepturi sed quidem et molestiae et.
Sapiente recusandae sint voluptas.
Aliquid nulla adipisci ut at id vel.
Corrupti voluptas deserunt laborum velit voluptas.
Quia iure voluptas.
Nulla voluptas et.
Harum rerum officiis eum molestiae.", OwnerId = 59, ProjectName = "mya.net" },
                        new { Id = 10, Description = @"Quod incidunt omnis sed.
Perspiciatis dolores est praesentium eveniet libero est voluptatem sit nam.
Quasi in id quam atque placeat aut natus natus.
Reiciendis est necessitatibus quibusdam facere voluptatem dolores.
Tempore provident et sint voluptate.
Animi quasi vel ut dolorum accusantium et vero dolorem.", OwnerId = 6, ProjectName = "jon.com" },
                        new { Id = 11, Description = @"Omnis doloribus quia doloribus rerum vel error quisquam.
Nam qui sint fugit est nisi magni quis voluptatem dolorem.
Illum velit quis voluptas itaque sed reiciendis quia id.
Veniam deserunt et qui est soluta velit molestias minima.
Numquam aut amet.
Sed aut repudiandae delectus excepturi eaque soluta ea.", OwnerId = 100, ProjectName = "devante.org" },
                        new { Id = 12, Description = @"Ex ab odit ea dignissimos fugit quae.
Omnis ducimus nostrum ipsa nam porro.
Officiis eos est itaque modi expedita error quo fuga.
Est similique sequi.
Animi aut sapiente quaerat veritatis illo blanditiis ipsum et est.
Eos suscipit et expedita dolorum molestiae pariatur voluptatem illum.
Vero et et consequuntur sapiente autem.
Atque reprehenderit quo unde.
Blanditiis tenetur rerum sit dolor animi nam ea nihil excepturi.
Quia vitae quia voluptates dolor consequatur vitae omnis magnam.", OwnerId = 34, ProjectName = "ian.net" },
                        new { Id = 13, Description = @"Dolores aut voluptatem.
Est ut recusandae eius.
Aut optio perferendis quis.
Dolore expedita esse repellendus.
Vel placeat ipsa quidem aut.
Voluptatum nemo beatae.
Iste sit non corrupti exercitationem.", OwnerId = 65, ProjectName = "jessyca.info" },
                        new { Id = 14, Description = @"Ad ut tenetur.
Dignissimos numquam dolorem porro itaque excepturi mollitia et expedita.
Laboriosam quis explicabo laudantium vel quia.
Non vero et eligendi.
Corrupti non doloribus et placeat aliquam magnam assumenda quasi.
Autem sed adipisci libero accusamus possimus consequatur error cumque harum.
Vel ratione consequatur omnis aperiam.", OwnerId = 2, ProjectName = "vernon.net" },
                        new { Id = 15, Description = @"Aperiam ratione culpa.
Quidem qui iusto voluptas nisi tempore rerum sit.
Dolores necessitatibus enim quo suscipit qui.
Exercitationem modi inventore quas cum vel maiores.
Quo ut nostrum delectus est officiis omnis inventore et rerum.
Doloremque recusandae et ea.
Voluptatum atque quisquam excepturi nam voluptas nemo fuga aliquid repellendus.
Vel sunt architecto ab quaerat quod corrupti ab.
Vel sint id.
Minus eum expedita assumenda aut quam et.", OwnerId = 50, ProjectName = "salvador.com" },
                        new { Id = 16, Description = @"Expedita voluptatum veniam hic.
Libero et itaque consequuntur hic ut ut saepe aut nostrum.
Placeat magnam qui iste debitis ipsum.
Quo odit ut cupiditate non nesciunt magnam rerum asperiores.
At animi ut.", OwnerId = 21, ProjectName = "bartholome.biz" },
                        new { Id = 17, Description = @"Libero molestiae repellendus eos sed.
Consequuntur magni sit maxime laborum molestias rem voluptatem corrupti.
Dignissimos voluptas iure ratione est dolor officiis alias.
Quos ipsa autem voluptatem ut facilis quasi officiis aliquam non.
Doloribus reiciendis doloribus libero in quibusdam aut molestias.
Atque in sed aut sunt.
Quaerat autem error laborum rerum iste repellendus rerum fuga.
Placeat aut rerum aspernatur ut quidem numquam odit placeat.
Totam at porro placeat saepe consequatur consequatur nam.
Repudiandae quas ut qui voluptatum iure.
Enim facilis quia sit quia.
Commodi quo est.
Accusantium voluptate quibusdam pariatur commodi molestiae ea et.
Voluptate beatae illum quisquam architecto.
Sed reprehenderit quo voluptas.
Distinctio rem quo voluptatem voluptas similique.", OwnerId = 79, ProjectName = "kendrick.info" },
                        new { Id = 18, Description = @"Aut aspernatur sed repellendus a accusamus.
Omnis architecto et qui sit reiciendis velit quos.
Magnam asperiores dicta cumque et molestias dolorem accusantium omnis eligendi.
Cupiditate autem facilis quibusdam commodi sint sint.
Porro sint nostrum incidunt.
Placeat nesciunt aliquam in.
Quis id veritatis.
Facilis provident sunt velit cum quo autem recusandae dolor.
Ut laboriosam sed possimus.
Aut eius ut inventore consequatur est.
A omnis quo hic quos magnam.", OwnerId = 60, ProjectName = "veda.biz" },
                        new { Id = 19, Description = @"Est voluptatem aut modi hic labore.
Qui repellendus laboriosam.
Delectus repudiandae et.
Dolorem laudantium at voluptatem cum inventore.
Ut in consequatur.
Qui nisi quia nisi modi sapiente enim.
Et id ipsam rerum ut doloremque aut sit maiores.
Eveniet quibusdam molestiae.
Sunt molestiae consequuntur aspernatur dolore.
Velit fuga sint sed esse.
Excepturi quod optio dignissimos fugit aspernatur.
Quae velit quibusdam molestias in qui asperiores cumque.
Architecto neque cum aut et voluptate aliquam optio numquam.
Porro doloremque blanditiis aut.
Dolor rem saepe sint ut corrupti ut a.
Qui aut quia nostrum sint unde sint aliquam culpa.
Unde possimus vero ea est aut corrupti.
Incidunt maiores vel et officia reprehenderit aut qui odit eligendi.
Totam iure provident sed aut accusamus.
Quis sapiente dolor nam laborum laudantium qui sint aliquam.", OwnerId = 94, ProjectName = "theodore.com" },
                        new { Id = 20, Description = @"Placeat corrupti enim ut quam sint.
Qui sit consectetur dignissimos dolorem.
Aut voluptatem sit iste reiciendis sed tenetur illum non.
Error autem sint quia.
Dolores dolor aut ipsa occaecati veritatis quisquam eveniet.
Incidunt laudantium ex deleniti.
Omnis officia modi temporibus nobis laboriosam voluptas.", OwnerId = 25, ProjectName = "garry.org" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProjectId");

                    b.Property<int>("Rating");

                    b.Property<int>("SkillId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectRequirments");

                    b.HasData(
                        new { Id = 1, Rating = 2, SkillId = 15 },
                        new { Id = 2, Rating = 4, SkillId = 15 },
                        new { Id = 3, Rating = 2, SkillId = 15 },
                        new { Id = 4, Rating = 1, SkillId = 10 },
                        new { Id = 5, Rating = 4, SkillId = 10 },
                        new { Id = 6, Rating = 2, SkillId = 13 },
                        new { Id = 7, Rating = 2, SkillId = 18 },
                        new { Id = 8, Rating = 2, SkillId = 15 },
                        new { Id = 9, Rating = 5, SkillId = 22 },
                        new { Id = 10, Rating = 5, SkillId = 13 },
                        new { Id = 11, Rating = 3, SkillId = 16 },
                        new { Id = 12, Rating = 4, SkillId = 24 },
                        new { Id = 13, Rating = 5, SkillId = 19 },
                        new { Id = 14, Rating = 3, SkillId = 24 },
                        new { Id = 15, Rating = 3, SkillId = 11 },
                        new { Id = 16, Rating = 2, SkillId = 18 },
                        new { Id = 17, Rating = 3, SkillId = 16 },
                        new { Id = 18, Rating = 3, SkillId = 18 },
                        new { Id = 19, Rating = 2, SkillId = 13 },
                        new { Id = 20, Rating = 5, SkillId = 6 },
                        new { Id = 21, Rating = 4, SkillId = 8 },
                        new { Id = 22, Rating = 1, SkillId = 15 },
                        new { Id = 23, Rating = 3, SkillId = 13 },
                        new { Id = 24, Rating = 5, SkillId = 10 },
                        new { Id = 25, Rating = 4, SkillId = 11 },
                        new { Id = 26, Rating = 1, SkillId = 1 },
                        new { Id = 27, Rating = 1, SkillId = 16 },
                        new { Id = 28, Rating = 3, SkillId = 4 },
                        new { Id = 29, Rating = 4, SkillId = 23 },
                        new { Id = 30, Rating = 4, SkillId = 2 },
                        new { Id = 31, Rating = 1, SkillId = 9 },
                        new { Id = 32, Rating = 1, SkillId = 4 },
                        new { Id = 33, Rating = 2, SkillId = 22 },
                        new { Id = 34, Rating = 1, SkillId = 15 },
                        new { Id = 35, Rating = 3, SkillId = 3 },
                        new { Id = 36, Rating = 3, SkillId = 3 },
                        new { Id = 37, Rating = 4, SkillId = 7 },
                        new { Id = 38, Rating = 4, SkillId = 12 }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SkillName");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new { Id = 1, SkillName = "C#" },
                        new { Id = 2, SkillName = "Haskel" },
                        new { Id = 3, SkillName = "Swift" },
                        new { Id = 4, SkillName = "Java" },
                        new { Id = 5, SkillName = "R" },
                        new { Id = 6, SkillName = "PHP" },
                        new { Id = 7, SkillName = "Assembly" },
                        new { Id = 8, SkillName = "Go" },
                        new { Id = 9, SkillName = "Ruby" },
                        new { Id = 10, SkillName = "Perl" },
                        new { Id = 11, SkillName = "MS-SQL" },
                        new { Id = 12, SkillName = "JavaScript" },
                        new { Id = 13, SkillName = "TypeScript" },
                        new { Id = 14, SkillName = "C" },
                        new { Id = 15, SkillName = "C++" },
                        new { Id = 16, SkillName = "Python" },
                        new { Id = 17, SkillName = "PL/SQL" },
                        new { Id = 18, SkillName = "MongoDb" },
                        new { Id = 19, SkillName = "Lisp" },
                        new { Id = 20, SkillName = "Prolog" },
                        new { Id = 21, SkillName = "D" },
                        new { Id = 22, SkillName = "Rust" },
                        new { Id = 23, SkillName = "Android" },
                        new { Id = 24, SkillName = ".Net" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<int>("GitHubId");

                    b.Property<string>("Login");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, GitHubId = 0, Login = "Jordan_Jenkins81" },
                        new { Id = 2, GitHubId = 0, Login = "Jonas.Mraz71" },
                        new { Id = 3, GitHubId = 0, Login = "Desiree.Hagenes" },
                        new { Id = 4, GitHubId = 0, Login = "Danny_Cummings4" },
                        new { Id = 5, GitHubId = 0, Login = "Blanca.Heller3" },
                        new { Id = 6, GitHubId = 0, Login = "Grace14" },
                        new { Id = 7, GitHubId = 0, Login = "Kathleen.Fisher99" },
                        new { Id = 8, GitHubId = 0, Login = "Jeffrey.Turner" },
                        new { Id = 9, GitHubId = 0, Login = "Sunny.Rempel" },
                        new { Id = 10, GitHubId = 0, Login = "Houston.Fadel81" },
                        new { Id = 11, GitHubId = 0, Login = "Stacey.Gibson32" },
                        new { Id = 12, GitHubId = 0, Login = "Zaria_Mante" },
                        new { Id = 13, GitHubId = 0, Login = "Lloyd.Yost28" },
                        new { Id = 14, GitHubId = 0, Login = "Emory81" },
                        new { Id = 15, GitHubId = 0, Login = "Tristian98" },
                        new { Id = 16, GitHubId = 0, Login = "Ibrahim_Schinner17" },
                        new { Id = 17, GitHubId = 0, Login = "Leola_Schamberger72" },
                        new { Id = 18, GitHubId = 0, Login = "Wilfred_McDermott" },
                        new { Id = 19, GitHubId = 0, Login = "Henry_Gibson80" },
                        new { Id = 20, GitHubId = 0, Login = "Makayla44" },
                        new { Id = 21, GitHubId = 0, Login = "Josiah.OReilly" },
                        new { Id = 22, GitHubId = 0, Login = "Russ_Considine" },
                        new { Id = 23, GitHubId = 0, Login = "Celestine_Kuphal92" },
                        new { Id = 24, GitHubId = 0, Login = "Houston_Krajcik54" },
                        new { Id = 25, GitHubId = 0, Login = "Alberto81" },
                        new { Id = 26, GitHubId = 0, Login = "Madelyn.OConner" },
                        new { Id = 27, GitHubId = 0, Login = "Alejandra7" },
                        new { Id = 28, GitHubId = 0, Login = "Mabel34" },
                        new { Id = 29, GitHubId = 0, Login = "Estevan.Dickens93" },
                        new { Id = 30, GitHubId = 0, Login = "Oda_Fritsch8" },
                        new { Id = 31, GitHubId = 0, Login = "Misael_Breitenberg" },
                        new { Id = 32, GitHubId = 0, Login = "Ian.Willms52" },
                        new { Id = 33, GitHubId = 0, Login = "Elroy.Denesik79" },
                        new { Id = 34, GitHubId = 0, Login = "Mohammad50" },
                        new { Id = 35, GitHubId = 0, Login = "Laverne.Boyle65" },
                        new { Id = 36, GitHubId = 0, Login = "King8" },
                        new { Id = 37, GitHubId = 0, Login = "Jamir71" },
                        new { Id = 38, GitHubId = 0, Login = "Eldridge_Altenwerth" },
                        new { Id = 39, GitHubId = 0, Login = "Edna46" },
                        new { Id = 40, GitHubId = 0, Login = "Cody_Ernser" },
                        new { Id = 41, GitHubId = 0, Login = "Rudolph.Cruickshank" },
                        new { Id = 42, GitHubId = 0, Login = "Triston64" },
                        new { Id = 43, GitHubId = 0, Login = "Naomi.Hills24" },
                        new { Id = 44, GitHubId = 0, Login = "Isabell.Walker87" },
                        new { Id = 45, GitHubId = 0, Login = "Geraldine59" },
                        new { Id = 46, GitHubId = 0, Login = "Silas_Powlowski" },
                        new { Id = 47, GitHubId = 0, Login = "Ian.Gaylord39" },
                        new { Id = 48, GitHubId = 0, Login = "Seth_Halvorson" },
                        new { Id = 49, GitHubId = 0, Login = "Hannah14" },
                        new { Id = 50, GitHubId = 0, Login = "Maye_Kub" },
                        new { Id = 51, GitHubId = 0, Login = "Tiana68" },
                        new { Id = 52, GitHubId = 0, Login = "Roman.Murazik" },
                        new { Id = 53, GitHubId = 0, Login = "Eric63" },
                        new { Id = 54, GitHubId = 0, Login = "Devonte_Goldner7" },
                        new { Id = 55, GitHubId = 0, Login = "Ericka_Swift97" },
                        new { Id = 56, GitHubId = 0, Login = "Rick_Waelchi51" },
                        new { Id = 57, GitHubId = 0, Login = "Dessie_Bayer2" },
                        new { Id = 58, GitHubId = 0, Login = "Malcolm.Mraz11" },
                        new { Id = 59, GitHubId = 0, Login = "Chester.Metz" },
                        new { Id = 60, GitHubId = 0, Login = "Myrl28" },
                        new { Id = 61, GitHubId = 0, Login = "Toy53" },
                        new { Id = 62, GitHubId = 0, Login = "Gabe_Bernhard" },
                        new { Id = 63, GitHubId = 0, Login = "Selena.Goyette41" },
                        new { Id = 64, GitHubId = 0, Login = "Adolph21" },
                        new { Id = 65, GitHubId = 0, Login = "Dillan0" },
                        new { Id = 66, GitHubId = 0, Login = "Wayne54" },
                        new { Id = 67, GitHubId = 0, Login = "Lisette.Tremblay28" },
                        new { Id = 68, GitHubId = 0, Login = "Verla_Treutel73" },
                        new { Id = 69, GitHubId = 0, Login = "Ayana_Hintz66" },
                        new { Id = 70, GitHubId = 0, Login = "Elmore.Jenkins1" },
                        new { Id = 71, GitHubId = 0, Login = "Theresia39" },
                        new { Id = 72, GitHubId = 0, Login = "Johnpaul.Feeney" },
                        new { Id = 73, GitHubId = 0, Login = "Shayne_Goyette83" },
                        new { Id = 74, GitHubId = 0, Login = "Xavier64" },
                        new { Id = 75, GitHubId = 0, Login = "Francisca5" },
                        new { Id = 76, GitHubId = 0, Login = "Marilie10" },
                        new { Id = 77, GitHubId = 0, Login = "Narciso_Kuhn" },
                        new { Id = 78, GitHubId = 0, Login = "Rosina30" },
                        new { Id = 79, GitHubId = 0, Login = "Electa_Mraz33" },
                        new { Id = 80, GitHubId = 0, Login = "Mustafa.Becker" },
                        new { Id = 81, GitHubId = 0, Login = "Sunny.Hermann54" },
                        new { Id = 82, GitHubId = 0, Login = "Myron_Waters" },
                        new { Id = 83, GitHubId = 0, Login = "Alysson95" },
                        new { Id = 84, GitHubId = 0, Login = "Dedric.Walker76" },
                        new { Id = 85, GitHubId = 0, Login = "Nannie.Torp" },
                        new { Id = 86, GitHubId = 0, Login = "Marjory_Rutherford" },
                        new { Id = 87, GitHubId = 0, Login = "Frederick.Schumm" },
                        new { Id = 88, GitHubId = 0, Login = "Liza_Lindgren77" },
                        new { Id = 89, GitHubId = 0, Login = "Heloise.Kunze75" },
                        new { Id = 90, GitHubId = 0, Login = "Maeve54" },
                        new { Id = 91, GitHubId = 0, Login = "Yvette.Grant" },
                        new { Id = 92, GitHubId = 0, Login = "Abdullah96" },
                        new { Id = 93, GitHubId = 0, Login = "Elvis_Miller67" },
                        new { Id = 94, GitHubId = 0, Login = "Abner37" },
                        new { Id = 95, GitHubId = 0, Login = "Beth.Batz" },
                        new { Id = 96, GitHubId = 0, Login = "Madie46" },
                        new { Id = 97, GitHubId = 0, Login = "Jevon_Jacobi" },
                        new { Id = 98, GitHubId = 0, Login = "Yessenia84" },
                        new { Id = 99, GitHubId = 0, Login = "Brianne19" },
                        new { Id = 100, GitHubId = 0, Login = "Yasmeen.Schulist" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserFollowers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FollowerId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.ToTable("UserFollowers");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Rating");

                    b.Property<int>("SkillId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");

                    b.HasData(
                        new { Id = 1, Rating = 1, SkillId = 7, UserId = 1 },
                        new { Id = 2, Rating = 5, SkillId = 19, UserId = 1 },
                        new { Id = 3, Rating = 1, SkillId = 10, UserId = 2 },
                        new { Id = 4, Rating = 2, SkillId = 22, UserId = 2 },
                        new { Id = 5, Rating = 0, SkillId = 1, UserId = 3 },
                        new { Id = 6, Rating = 3, SkillId = 11, UserId = 3 },
                        new { Id = 7, Rating = 2, SkillId = 9, UserId = 3 },
                        new { Id = 8, Rating = 0, SkillId = 14, UserId = 4 },
                        new { Id = 9, Rating = 4, SkillId = 10, UserId = 5 },
                        new { Id = 10, Rating = 0, SkillId = 19, UserId = 6 },
                        new { Id = 11, Rating = 5, SkillId = 14, UserId = 6 },
                        new { Id = 12, Rating = 4, SkillId = 23, UserId = 6 },
                        new { Id = 13, Rating = 3, SkillId = 18, UserId = 7 },
                        new { Id = 14, Rating = 0, SkillId = 1, UserId = 7 },
                        new { Id = 15, Rating = 1, SkillId = 2, UserId = 8 },
                        new { Id = 16, Rating = 3, SkillId = 7, UserId = 9 },
                        new { Id = 17, Rating = 5, SkillId = 25, UserId = 9 },
                        new { Id = 18, Rating = 1, SkillId = 7, UserId = 9 },
                        new { Id = 19, Rating = 5, SkillId = 7, UserId = 10 },
                        new { Id = 20, Rating = 4, SkillId = 10, UserId = 10 },
                        new { Id = 21, Rating = 1, SkillId = 12, UserId = 10 },
                        new { Id = 22, Rating = 3, SkillId = 15, UserId = 11 },
                        new { Id = 23, Rating = 4, SkillId = 3, UserId = 12 },
                        new { Id = 24, Rating = 4, SkillId = 3, UserId = 13 },
                        new { Id = 25, Rating = 1, SkillId = 25, UserId = 13 },
                        new { Id = 26, Rating = 2, SkillId = 14, UserId = 14 },
                        new { Id = 27, Rating = 4, SkillId = 14, UserId = 15 },
                        new { Id = 28, Rating = 0, SkillId = 25, UserId = 15 },
                        new { Id = 29, Rating = 2, SkillId = 18, UserId = 15 },
                        new { Id = 30, Rating = 3, SkillId = 1, UserId = 16 },
                        new { Id = 31, Rating = 4, SkillId = 14, UserId = 16 },
                        new { Id = 32, Rating = 0, SkillId = 6, UserId = 16 },
                        new { Id = 33, Rating = 5, SkillId = 22, UserId = 17 },
                        new { Id = 34, Rating = 2, SkillId = 24, UserId = 17 },
                        new { Id = 35, Rating = 4, SkillId = 7, UserId = 17 },
                        new { Id = 36, Rating = 2, SkillId = 22, UserId = 17 },
                        new { Id = 37, Rating = 4, SkillId = 6, UserId = 19 },
                        new { Id = 38, Rating = 3, SkillId = 2, UserId = 19 },
                        new { Id = 39, Rating = 2, SkillId = 20, UserId = 20 },
                        new { Id = 40, Rating = 1, SkillId = 2, UserId = 20 },
                        new { Id = 41, Rating = 3, SkillId = 11, UserId = 20 },
                        new { Id = 42, Rating = 1, SkillId = 9, UserId = 21 },
                        new { Id = 43, Rating = 4, SkillId = 21, UserId = 21 },
                        new { Id = 44, Rating = 0, SkillId = 4, UserId = 21 },
                        new { Id = 45, Rating = 1, SkillId = 24, UserId = 22 },
                        new { Id = 46, Rating = 4, SkillId = 4, UserId = 22 },
                        new { Id = 47, Rating = 4, SkillId = 2, UserId = 22 },
                        new { Id = 48, Rating = 3, SkillId = 5, UserId = 23 },
                        new { Id = 49, Rating = 2, SkillId = 2, UserId = 24 },
                        new { Id = 50, Rating = 1, SkillId = 22, UserId = 24 },
                        new { Id = 51, Rating = 0, SkillId = 21, UserId = 24 },
                        new { Id = 52, Rating = 3, SkillId = 2, UserId = 25 },
                        new { Id = 53, Rating = 2, SkillId = 19, UserId = 27 },
                        new { Id = 54, Rating = 4, SkillId = 5, UserId = 27 },
                        new { Id = 55, Rating = 5, SkillId = 4, UserId = 28 },
                        new { Id = 56, Rating = 0, SkillId = 21, UserId = 31 },
                        new { Id = 57, Rating = 0, SkillId = 6, UserId = 31 },
                        new { Id = 58, Rating = 1, SkillId = 19, UserId = 31 },
                        new { Id = 59, Rating = 1, SkillId = 11, UserId = 32 },
                        new { Id = 60, Rating = 2, SkillId = 21, UserId = 32 },
                        new { Id = 61, Rating = 0, SkillId = 3, UserId = 32 },
                        new { Id = 62, Rating = 3, SkillId = 5, UserId = 32 },
                        new { Id = 63, Rating = 0, SkillId = 5, UserId = 32 },
                        new { Id = 64, Rating = 5, SkillId = 25, UserId = 33 },
                        new { Id = 65, Rating = 0, SkillId = 18, UserId = 34 },
                        new { Id = 66, Rating = 3, SkillId = 19, UserId = 34 },
                        new { Id = 67, Rating = 3, SkillId = 21, UserId = 35 },
                        new { Id = 68, Rating = 0, SkillId = 9, UserId = 36 },
                        new { Id = 69, Rating = 0, SkillId = 11, UserId = 36 },
                        new { Id = 70, Rating = 3, SkillId = 25, UserId = 37 },
                        new { Id = 71, Rating = 0, SkillId = 13, UserId = 37 },
                        new { Id = 72, Rating = 0, SkillId = 20, UserId = 38 },
                        new { Id = 73, Rating = 4, SkillId = 8, UserId = 38 },
                        new { Id = 74, Rating = 3, SkillId = 9, UserId = 39 },
                        new { Id = 75, Rating = 3, SkillId = 19, UserId = 39 },
                        new { Id = 76, Rating = 2, SkillId = 19, UserId = 40 },
                        new { Id = 77, Rating = 1, SkillId = 11, UserId = 40 },
                        new { Id = 78, Rating = 0, SkillId = 16, UserId = 40 },
                        new { Id = 79, Rating = 3, SkillId = 3, UserId = 42 },
                        new { Id = 80, Rating = 1, SkillId = 18, UserId = 42 },
                        new { Id = 81, Rating = 1, SkillId = 8, UserId = 43 },
                        new { Id = 82, Rating = 3, SkillId = 15, UserId = 43 },
                        new { Id = 83, Rating = 3, SkillId = 4, UserId = 43 },
                        new { Id = 84, Rating = 5, SkillId = 2, UserId = 44 },
                        new { Id = 85, Rating = 4, SkillId = 4, UserId = 44 },
                        new { Id = 86, Rating = 1, SkillId = 9, UserId = 45 },
                        new { Id = 87, Rating = 0, SkillId = 18, UserId = 45 },
                        new { Id = 88, Rating = 3, SkillId = 14, UserId = 46 },
                        new { Id = 89, Rating = 4, SkillId = 1, UserId = 46 },
                        new { Id = 90, Rating = 2, SkillId = 16, UserId = 46 },
                        new { Id = 91, Rating = 2, SkillId = 24, UserId = 47 },
                        new { Id = 92, Rating = 1, SkillId = 21, UserId = 48 },
                        new { Id = 93, Rating = 1, SkillId = 4, UserId = 48 },
                        new { Id = 94, Rating = 0, SkillId = 13, UserId = 49 },
                        new { Id = 95, Rating = 0, SkillId = 5, UserId = 50 },
                        new { Id = 96, Rating = 2, SkillId = 11, UserId = 50 },
                        new { Id = 97, Rating = 0, SkillId = 2, UserId = 51 },
                        new { Id = 98, Rating = 0, SkillId = 1, UserId = 51 },
                        new { Id = 99, Rating = 0, SkillId = 18, UserId = 51 },
                        new { Id = 100, Rating = 2, SkillId = 7, UserId = 52 },
                        new { Id = 101, Rating = 0, SkillId = 7, UserId = 53 },
                        new { Id = 102, Rating = 0, SkillId = 20, UserId = 54 },
                        new { Id = 103, Rating = 4, SkillId = 23, UserId = 54 },
                        new { Id = 104, Rating = 1, SkillId = 1, UserId = 56 },
                        new { Id = 105, Rating = 2, SkillId = 7, UserId = 56 },
                        new { Id = 106, Rating = 5, SkillId = 23, UserId = 57 },
                        new { Id = 107, Rating = 5, SkillId = 4, UserId = 57 },
                        new { Id = 108, Rating = 5, SkillId = 5, UserId = 57 },
                        new { Id = 109, Rating = 1, SkillId = 17, UserId = 58 },
                        new { Id = 110, Rating = 5, SkillId = 24, UserId = 60 },
                        new { Id = 111, Rating = 5, SkillId = 10, UserId = 60 },
                        new { Id = 112, Rating = 1, SkillId = 4, UserId = 61 },
                        new { Id = 113, Rating = 0, SkillId = 14, UserId = 61 },
                        new { Id = 114, Rating = 0, SkillId = 25, UserId = 61 },
                        new { Id = 115, Rating = 0, SkillId = 8, UserId = 61 },
                        new { Id = 116, Rating = 1, SkillId = 2, UserId = 62 },
                        new { Id = 117, Rating = 4, SkillId = 5, UserId = 63 },
                        new { Id = 118, Rating = 0, SkillId = 13, UserId = 63 },
                        new { Id = 119, Rating = 4, SkillId = 20, UserId = 63 },
                        new { Id = 120, Rating = 2, SkillId = 9, UserId = 66 },
                        new { Id = 121, Rating = 4, SkillId = 24, UserId = 66 },
                        new { Id = 122, Rating = 5, SkillId = 9, UserId = 66 },
                        new { Id = 123, Rating = 1, SkillId = 3, UserId = 67 },
                        new { Id = 124, Rating = 2, SkillId = 5, UserId = 67 },
                        new { Id = 125, Rating = 5, SkillId = 22, UserId = 68 },
                        new { Id = 126, Rating = 3, SkillId = 3, UserId = 68 },
                        new { Id = 127, Rating = 4, SkillId = 23, UserId = 69 },
                        new { Id = 128, Rating = 2, SkillId = 21, UserId = 69 },
                        new { Id = 129, Rating = 0, SkillId = 5, UserId = 71 },
                        new { Id = 130, Rating = 4, SkillId = 13, UserId = 71 },
                        new { Id = 131, Rating = 4, SkillId = 6, UserId = 72 },
                        new { Id = 132, Rating = 4, SkillId = 11, UserId = 72 },
                        new { Id = 133, Rating = 2, SkillId = 16, UserId = 72 },
                        new { Id = 134, Rating = 2, SkillId = 15, UserId = 73 },
                        new { Id = 135, Rating = 1, SkillId = 6, UserId = 73 },
                        new { Id = 136, Rating = 0, SkillId = 16, UserId = 74 },
                        new { Id = 137, Rating = 2, SkillId = 14, UserId = 76 },
                        new { Id = 138, Rating = 1, SkillId = 22, UserId = 76 },
                        new { Id = 139, Rating = 4, SkillId = 11, UserId = 77 },
                        new { Id = 140, Rating = 5, SkillId = 15, UserId = 77 },
                        new { Id = 141, Rating = 4, SkillId = 10, UserId = 78 },
                        new { Id = 142, Rating = 1, SkillId = 8, UserId = 78 },
                        new { Id = 143, Rating = 0, SkillId = 10, UserId = 79 },
                        new { Id = 144, Rating = 3, SkillId = 7, UserId = 79 },
                        new { Id = 145, Rating = 0, SkillId = 6, UserId = 79 },
                        new { Id = 146, Rating = 1, SkillId = 6, UserId = 80 },
                        new { Id = 147, Rating = 5, SkillId = 11, UserId = 80 },
                        new { Id = 148, Rating = 1, SkillId = 1, UserId = 80 },
                        new { Id = 149, Rating = 2, SkillId = 1, UserId = 81 },
                        new { Id = 150, Rating = 3, SkillId = 1, UserId = 81 },
                        new { Id = 151, Rating = 2, SkillId = 24, UserId = 82 },
                        new { Id = 152, Rating = 4, SkillId = 19, UserId = 83 },
                        new { Id = 153, Rating = 0, SkillId = 7, UserId = 84 },
                        new { Id = 154, Rating = 3, SkillId = 8, UserId = 84 },
                        new { Id = 155, Rating = 4, SkillId = 25, UserId = 85 },
                        new { Id = 156, Rating = 2, SkillId = 8, UserId = 85 },
                        new { Id = 157, Rating = 1, SkillId = 15, UserId = 85 },
                        new { Id = 158, Rating = 5, SkillId = 25, UserId = 86 },
                        new { Id = 159, Rating = 4, SkillId = 2, UserId = 87 },
                        new { Id = 160, Rating = 1, SkillId = 6, UserId = 87 },
                        new { Id = 161, Rating = 1, SkillId = 8, UserId = 87 },
                        new { Id = 162, Rating = 2, SkillId = 15, UserId = 88 },
                        new { Id = 163, Rating = 1, SkillId = 14, UserId = 88 },
                        new { Id = 164, Rating = 2, SkillId = 2, UserId = 88 },
                        new { Id = 165, Rating = 1, SkillId = 16, UserId = 89 },
                        new { Id = 166, Rating = 4, SkillId = 19, UserId = 89 },
                        new { Id = 167, Rating = 1, SkillId = 9, UserId = 89 },
                        new { Id = 168, Rating = 0, SkillId = 22, UserId = 89 },
                        new { Id = 169, Rating = 2, SkillId = 6, UserId = 91 },
                        new { Id = 170, Rating = 0, SkillId = 19, UserId = 92 },
                        new { Id = 171, Rating = 2, SkillId = 9, UserId = 93 },
                        new { Id = 172, Rating = 4, SkillId = 6, UserId = 93 },
                        new { Id = 173, Rating = 4, SkillId = 24, UserId = 96 },
                        new { Id = 174, Rating = 4, SkillId = 5, UserId = 96 },
                        new { Id = 175, Rating = 2, SkillId = 11, UserId = 97 },
                        new { Id = 176, Rating = 5, SkillId = 14, UserId = 97 },
                        new { Id = 177, Rating = 3, SkillId = 18, UserId = 97 },
                        new { Id = 178, Rating = 5, SkillId = 8, UserId = 98 },
                        new { Id = 179, Rating = 0, SkillId = 25, UserId = 98 },
                        new { Id = 180, Rating = 4, SkillId = 5, UserId = 99 },
                        new { Id = 181, Rating = 4, SkillId = 1, UserId = 99 },
                        new { Id = 182, Rating = 1, SkillId = 9, UserId = 99 },
                        new { Id = 183, Rating = 0, SkillId = 1, UserId = 99 },
                        new { Id = 184, Rating = 3, SkillId = 14, UserId = 99 }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectMember", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collaboo.App.WebAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectRequirement", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Project")
                        .WithMany("Requirements")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Collaboo.App.WebAPI.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserFollowers", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Follower", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserSkills", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collaboo.App.WebAPI.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
