// <auto-generated />
using System;
using Collaboo.App.WebAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Collaboo.App.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181118033822_Seed3")]
    partial class Seed3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:Sequence:.Id", "'Id', '', '1000', '5', '', '', 'Int32', 'False'");

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Follower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("GitHubRepoUrl");

                    b.Property<int>("OwnerId");

                    b.Property<string>("ProjectName");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new { Id = 1, Description = @"Dolorum illo ab quaerat sunt vel sint ut nihil deleniti.
Et recusandae velit.
Vel magnam quam.
Sed ducimus rem iste.
Placeat eos non dolor necessitatibus quia et.
Autem et adipisci est eligendi ex.
Nobis alias nesciunt nemo magnam ut facilis veritatis.
Sint explicabo consequatur id blanditiis natus occaecati ratione dolores.
Excepturi incidunt ipsum laboriosam perferendis corporis esse.
Magnam magni consequatur reprehenderit sed saepe id.
Sed quis neque nemo laborum aut.
Reprehenderit quaerat autem facere voluptas a illum minima quae.
Sequi nulla qui sint.
Qui consequatur fugiat nemo qui recusandae vel non.
Rem repellat aut ex ut voluptatibus consectetur molestiae velit iusto.
Vitae modi omnis sunt rerum et pariatur a neque.
Ab quis delectus ut qui nesciunt rem corporis nihil et.", OwnerId = 58, ProjectName = "morgan.net" },
                        new { Id = 2, Description = @"Voluptatibus praesentium quae veritatis aperiam.
Et perferendis id qui.
Blanditiis maxime libero sapiente vitae at consequatur consequatur nihil quo.
Illum sunt qui.
Fuga nihil sunt velit aliquid ea enim omnis.
Aut aut saepe consequuntur quod et enim tempora.
Modi nihil est quidem maxime dolor est commodi vel vero.
Aut facilis a et ipsam id est.
Sed incidunt occaecati sit maiores aut.", OwnerId = 99, ProjectName = "douglas.org" },
                        new { Id = 3, Description = @"Aut odio dolor eos et.
Asperiores maiores sapiente.
Voluptatum maiores officia esse qui soluta voluptas pariatur et.
Eos saepe eum est est cumque cupiditate id fuga.
Molestias omnis consequuntur perspiciatis ab dolor consectetur dolor sunt.
Voluptatem et voluptas.
Veritatis dolore non assumenda nulla sit distinctio molestiae.
Molestiae magni repudiandae est sunt.", OwnerId = 14, ProjectName = "casper.name" },
                        new { Id = 4, Description = @"Quia veniam quo eos ipsa.
Sapiente corrupti unde possimus non.
Occaecati consequuntur ipsum et deleniti est.
Saepe exercitationem explicabo beatae blanditiis cumque esse eos similique.
Facilis molestiae non.
Quaerat natus autem.
Iure rerum ea aut voluptas.
Libero omnis recusandae.
Repellendus odio laudantium distinctio reprehenderit quo ea.", OwnerId = 7, ProjectName = "berneice.biz" },
                        new { Id = 5, Description = @"Et tempora reprehenderit iure.
Fugiat repellat molestiae quaerat similique quibusdam veniam explicabo rerum aliquid.
Blanditiis maiores voluptate.
Voluptas aut aliquid magni quidem maiores provident est.
Adipisci qui ipsum sunt modi quaerat dolor corrupti.
Quia quo omnis quas ut eius.
Dolor similique molestias corrupti ut est consequuntur quibusdam.
Qui qui officiis voluptatem facere et corporis.
Est et fugit et adipisci.", OwnerId = 87, ProjectName = "lloyd.biz" },
                        new { Id = 6, Description = @"Omnis sunt ut.
Praesentium magni quos praesentium esse.
Sed ex qui.
Quis excepturi eum iusto corporis.
Cumque quis provident totam.
Veniam aut aut maiores cumque debitis ipsam illum est.
Modi cum dolores commodi maxime.
Exercitationem quas ad odit quis atque temporibus aliquam soluta.
Consectetur accusamus corporis.
Corrupti eaque et atque quia.
Deleniti rem porro.
Rerum sed reiciendis reiciendis.
Fugiat optio architecto natus.", OwnerId = 46, ProjectName = "gwen.net" },
                        new { Id = 7, Description = @"Voluptate quibusdam ipsam possimus corporis.
Nobis dignissimos sint nemo vero amet et est.
Porro quis qui repellendus.
Eius fugiat molestias vel.
Pariatur laboriosam sed.
Nulla saepe nihil dolor quasi.
Autem quo est.
Illo laudantium dignissimos voluptatem.
Sed delectus deserunt quae necessitatibus voluptas dolorem qui.", OwnerId = 1, ProjectName = "brandy.com" },
                        new { Id = 8, Description = @"Et est blanditiis voluptatem similique.
Tempore velit sequi ea.
Sunt consequatur consequatur natus.
Qui libero omnis vel quo optio qui aliquam.
Tempora totam cum nemo nihil.
Non quas dicta non architecto quo id saepe.
Ut quaerat sapiente error quam.
Beatae quo id recusandae enim praesentium.
Omnis blanditiis aut molestias velit.
Laboriosam nam asperiores.
Qui maxime et.
Est autem corrupti.
Asperiores est totam laudantium in minus in quo qui voluptatem.
Quasi autem et adipisci error maxime harum voluptate.", OwnerId = 57, ProjectName = "jordi.net" },
                        new { Id = 9, Description = @"Ex nesciunt molestias illum dolor ea ex quae.
Asperiores minima nobis.
Exercitationem debitis quasi non commodi quia consectetur aperiam et est.
Omnis cum quia.
Eum et nihil.
Modi eum aut quam modi.
Expedita esse quibusdam officia hic vel sequi excepturi libero.
Facere suscipit quidem sequi quas ea.
Et et corrupti ut et beatae voluptatem.
Velit sunt asperiores praesentium quasi amet blanditiis pariatur.
Nihil temporibus qui ducimus.
Ut accusamus ipsa aut debitis laboriosam ab veniam enim dolor.
Eius cum doloribus id dolores nesciunt suscipit provident molestiae.", OwnerId = 76, ProjectName = "rahsaan.com" },
                        new { Id = 10, Description = @"Quaerat ullam corrupti laudantium ducimus quo delectus.
Praesentium vitae dolorum tempora.
Sed et est sint ullam non.
Pariatur excepturi laudantium aut cum unde blanditiis.
Occaecati modi sed impedit asperiores velit et eaque error.", OwnerId = 82, ProjectName = "rene.com" },
                        new { Id = 11, Description = @"Numquam et sed.
Libero magni est voluptatem fugiat.
Hic qui placeat placeat fugiat autem temporibus.
Aliquam aut rerum labore perspiciatis voluptates ut beatae officia rerum.
Explicabo voluptatum qui.
Temporibus exercitationem iste doloribus voluptate debitis quia magnam.
Iure doloremque omnis ut.
Et sed amet doloremque et vel quibusdam quam.
Commodi quia aperiam deserunt perspiciatis est enim id doloremque aut.
Sapiente blanditiis minima iure eum voluptatem recusandae pariatur odio.
Sint voluptatem eligendi esse quisquam soluta eos et iste.
Ut quis voluptatem adipisci repellendus.
Quis dolor non non est.
Tenetur temporibus cumque velit molestiae et facilis eveniet aut rerum.
Quia nulla illo nisi quia dolorem ipsa velit tempore voluptatum.
At officia dolores vitae animi perferendis.
Voluptatem quia molestias sed sint velit ut porro.
Facere veritatis quam expedita qui.
Reprehenderit velit aliquid qui accusantium fugit a atque occaecati aut.", OwnerId = 53, ProjectName = "jayne.org" },
                        new { Id = 12, Description = @"Nulla velit harum neque qui.
Rem sint sit vero odio praesentium sint.
Aliquid magnam illum sit eveniet.
Itaque minus officiis doloribus.
Adipisci voluptas doloribus tempora doloribus quo delectus.
Doloremque voluptates eos temporibus quos est sit.", OwnerId = 93, ProjectName = "dulce.com" },
                        new { Id = 13, Description = @"Et odio adipisci dolorem est impedit laudantium.
Repudiandae laboriosam fugit.
Facilis ut provident dolor deleniti.
Laboriosam ratione rem at atque vel corrupti laudantium.
Exercitationem similique ad distinctio quo.
Ea ut facere.
Qui quas minima dolore non est eligendi quibusdam.
Ratione hic adipisci unde odio officia cum.
Aut quibusdam a vel soluta quaerat eum ipsum.
Rerum soluta in quia labore sunt.
Dolores distinctio sit inventore eveniet perspiciatis dolorem autem qui.
Voluptatem quis aspernatur voluptatem fugiat quasi aperiam ad nostrum ipsum.
Fugiat eos dolore eveniet beatae praesentium quae aut qui.
Et autem esse velit.
Ea et eum similique harum dolorem tempora qui earum.
Quasi dignissimos consequatur.
Consequatur ab rerum ea voluptatibus corporis occaecati.
Neque illum vitae sed dolor consectetur id velit repellat soluta.", OwnerId = 62, ProjectName = "americo.name" },
                        new { Id = 14, Description = @"Est sed et id velit corporis.
Aut sit ut in doloremque neque sapiente aut iusto aut.
Laudantium qui perferendis atque sint.
Eaque doloribus non perferendis iure fugiat.
Rerum hic id modi et aliquid optio aut harum.
Consequatur et aut eum neque.
Qui voluptatem dolore quas autem velit sapiente.
Labore voluptatem et error nihil omnis.
Dolorum sit deleniti qui beatae natus id odit dicta.
Voluptatem fugiat quia sed quam harum.
Debitis esse beatae.", OwnerId = 100, ProjectName = "bryce.biz" },
                        new { Id = 15, Description = @"Doloribus quia voluptatibus nulla odit magni nobis vero.
Amet aut ea non vitae sit.
Sint nesciunt dicta facilis consequatur temporibus tempora illum.
Et est aut optio debitis deleniti.
Sint nihil sunt iure possimus voluptatem reiciendis veniam laudantium.
Omnis perferendis sed tempora quasi autem qui consequatur architecto voluptatibus.
Voluptatem vel velit rerum.
Blanditiis et dignissimos cum.
Sed impedit doloremque necessitatibus.
Asperiores harum a expedita.
Aut dolor reprehenderit doloremque.
Veniam neque ipsum saepe.
Sit et dolores est adipisci voluptas necessitatibus.
Deserunt aut aut voluptas temporibus illum.
Corporis molestias laboriosam pariatur.
Voluptas voluptate quam et odio qui maiores ipsum qui.
Exercitationem optio unde et eum id numquam quam optio saepe.
Consectetur commodi pariatur.
Sapiente reprehenderit in.
Voluptates est qui quia sunt nulla et vel eligendi.", OwnerId = 18, ProjectName = "amely.info" },
                        new { Id = 16, Description = @"Quo excepturi esse nostrum est maiores corrupti sunt.
Facilis tenetur optio.
Quae sunt minus voluptatum facere voluptate consequatur.
Aut rem autem blanditiis eius et ex occaecati magnam.
Omnis vel deleniti et laboriosam expedita libero libero.
Ipsam illum nobis quia quis qui ut.
Consequatur sapiente eligendi ullam recusandae ex necessitatibus animi eaque eaque.
Quas vitae dolores sunt quo alias in voluptatem aspernatur.
Ut architecto aut vitae illum ab.
Nihil exercitationem consequatur.
Tenetur doloremque unde.
Iste nisi dolorum accusantium officia ab ullam.
Fugiat dolorem molestias sit dolore nulla quia.
Architecto dolorem deleniti in rerum necessitatibus eius fugit nemo necessitatibus.
Quod aperiam est unde.
Qui perferendis veniam.", OwnerId = 66, ProjectName = "orval.biz" },
                        new { Id = 17, Description = @"Recusandae praesentium aut sint enim.
Possimus culpa sed aperiam maiores repellendus unde ut tempore.
Consequuntur quas quisquam cumque officiis iste qui veritatis.
Blanditiis mollitia incidunt natus occaecati consectetur repellendus.
Eos rerum molestiae repudiandae ullam aut iusto magni.
Dolorum alias repellendus voluptas quas laborum nisi.
Provident ad sunt consequatur rem vel debitis.
Corporis at ad cupiditate sit animi voluptas sed consequuntur velit.
Et facere eum cumque veniam.
Ad recusandae culpa minima pariatur tenetur voluptatibus.
Rerum doloribus sint non nulla libero voluptatem unde consequatur asperiores.
Neque est culpa voluptatem nesciunt culpa quidem explicabo veniam aspernatur.
Cumque in nostrum et adipisci dignissimos exercitationem et qui.", OwnerId = 91, ProjectName = "eladio.name" },
                        new { Id = 18, Description = @"Molestiae asperiores minima quod et eligendi maxime.
Facere sed sapiente eligendi repudiandae nihil cumque non vero.
Temporibus vitae quis laboriosam sint id rem qui.
Autem ut quae officiis aut.
Voluptate incidunt qui ex aliquid numquam ea.
Accusamus dolorem quia.", OwnerId = 29, ProjectName = "jewell.name" },
                        new { Id = 19, Description = @"Et ipsa deserunt nulla doloribus voluptas qui beatae cum enim.
Odio quis nostrum nihil.
Doloribus sit molestias consectetur.
At molestias atque.
Sapiente esse sint maxime quia ut.
Eum dignissimos ullam alias minima.
Occaecati vitae est molestias.
Vitae ut delectus placeat in sed molestiae nostrum.
Voluptatem soluta illum iure sed.
Laudantium accusantium voluptates.
Suscipit ex ullam.
Illo molestiae asperiores cumque ut eos distinctio molestiae perspiciatis est.
Molestiae sint quam numquam.
In illum doloremque et enim nihil et repudiandae totam.
Nam dolores ipsum culpa.
Voluptas dolor perferendis voluptates.
Qui quam a et expedita mollitia dolores non numquam.
Mollitia ipsa vel.", OwnerId = 7, ProjectName = "marcia.name" },
                        new { Id = 20, Description = @"Nobis aliquid exercitationem beatae incidunt et velit dolorem.
Delectus et nulla facilis quas.
Iure aliquam reiciendis vero animi asperiores cum.
Quam cumque ea similique dolorum soluta aut.
Expedita alias dolores voluptas iste non quas amet sequi incidunt.
Nisi ipsum omnis consequatur laudantium explicabo.
Nihil vel eligendi expedita est et aut.
Officiis vel officiis incidunt in corrupti voluptatem inventore omnis.
Excepturi quia tenetur vero placeat autem cumque consequatur quas.
In facilis suscipit eveniet voluptatum.", OwnerId = 9, ProjectName = "dereck.biz" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProjectId");

                    b.Property<int>("Rating");

                    b.Property<int>("SkillId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectRequirments");

                    b.HasData(
                        new { Id = 1, Rating = 5, SkillId = 7 },
                        new { Id = 2, Rating = 2, SkillId = 19 },
                        new { Id = 3, Rating = 1, SkillId = 8 },
                        new { Id = 4, Rating = 4, SkillId = 1 },
                        new { Id = 5, Rating = 3, SkillId = 23 },
                        new { Id = 6, Rating = 3, SkillId = 14 },
                        new { Id = 7, Rating = 5, SkillId = 9 },
                        new { Id = 8, Rating = 2, SkillId = 6 },
                        new { Id = 9, Rating = 4, SkillId = 12 },
                        new { Id = 10, Rating = 5, SkillId = 19 },
                        new { Id = 11, Rating = 1, SkillId = 21 },
                        new { Id = 12, Rating = 4, SkillId = 12 },
                        new { Id = 13, Rating = 4, SkillId = 12 },
                        new { Id = 14, Rating = 4, SkillId = 20 },
                        new { Id = 15, Rating = 3, SkillId = 13 },
                        new { Id = 16, Rating = 2, SkillId = 8 },
                        new { Id = 17, Rating = 2, SkillId = 16 },
                        new { Id = 18, Rating = 3, SkillId = 2 },
                        new { Id = 19, Rating = 1, SkillId = 19 },
                        new { Id = 20, Rating = 2, SkillId = 23 },
                        new { Id = 21, Rating = 1, SkillId = 10 },
                        new { Id = 22, Rating = 3, SkillId = 5 },
                        new { Id = 23, Rating = 4, SkillId = 13 },
                        new { Id = 24, Rating = 2, SkillId = 1 },
                        new { Id = 25, Rating = 3, SkillId = 16 },
                        new { Id = 26, Rating = 4, SkillId = 16 },
                        new { Id = 27, Rating = 2, SkillId = 19 },
                        new { Id = 28, Rating = 3, SkillId = 4 },
                        new { Id = 29, Rating = 4, SkillId = 20 },
                        new { Id = 30, Rating = 5, SkillId = 1 },
                        new { Id = 31, Rating = 1, SkillId = 8 },
                        new { Id = 32, Rating = 5, SkillId = 21 },
                        new { Id = 33, Rating = 1, SkillId = 8 },
                        new { Id = 34, Rating = 5, SkillId = 8 },
                        new { Id = 35, Rating = 1, SkillId = 6 },
                        new { Id = 36, Rating = 4, SkillId = 12 },
                        new { Id = 37, Rating = 5, SkillId = 15 },
                        new { Id = 38, Rating = 5, SkillId = 7 },
                        new { Id = 39, Rating = 1, SkillId = 23 },
                        new { Id = 40, Rating = 1, SkillId = 4 }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SkillName");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new { Id = 1, SkillName = "C#" },
                        new { Id = 2, SkillName = "Haskel" },
                        new { Id = 3, SkillName = "Swift" },
                        new { Id = 4, SkillName = "Java" },
                        new { Id = 5, SkillName = "R" },
                        new { Id = 6, SkillName = "PHP" },
                        new { Id = 7, SkillName = "Assembly" },
                        new { Id = 8, SkillName = "Go" },
                        new { Id = 9, SkillName = "Ruby" },
                        new { Id = 10, SkillName = "Perl" },
                        new { Id = 11, SkillName = "MS-SQL" },
                        new { Id = 12, SkillName = "JavaScript" },
                        new { Id = 13, SkillName = "TypeScript" },
                        new { Id = 14, SkillName = "C" },
                        new { Id = 15, SkillName = "C++" },
                        new { Id = 16, SkillName = "Python" },
                        new { Id = 17, SkillName = "PL/SQL" },
                        new { Id = 18, SkillName = "MongoDb" },
                        new { Id = 19, SkillName = "Lisp" },
                        new { Id = 20, SkillName = "Prolog" },
                        new { Id = 21, SkillName = "D" },
                        new { Id = 22, SkillName = "Rust" },
                        new { Id = 23, SkillName = "Android" },
                        new { Id = 24, SkillName = ".Net" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<int>("GitHubId");

                    b.Property<string>("Login");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, GitHubId = 0, Login = "Katlyn_Terry13" },
                        new { Id = 2, GitHubId = 0, Login = "Arlene.Anderson" },
                        new { Id = 3, GitHubId = 0, Login = "Ellie.Hodkiewicz57" },
                        new { Id = 4, GitHubId = 0, Login = "Jeramie.Toy58" },
                        new { Id = 5, GitHubId = 0, Login = "Orpha.Osinski" },
                        new { Id = 6, GitHubId = 0, Login = "Krystina86" },
                        new { Id = 7, GitHubId = 0, Login = "Dorothea46" },
                        new { Id = 8, GitHubId = 0, Login = "Baron_Orn40" },
                        new { Id = 9, GitHubId = 0, Login = "Hilario.Green41" },
                        new { Id = 10, GitHubId = 0, Login = "Friedrich_Boehm93" },
                        new { Id = 11, GitHubId = 0, Login = "Gwendolyn.Jaskolski" },
                        new { Id = 12, GitHubId = 0, Login = "Amelie_Kovacek" },
                        new { Id = 13, GitHubId = 0, Login = "Ceasar.Upton25" },
                        new { Id = 14, GitHubId = 0, Login = "Ashleigh_Effertz81" },
                        new { Id = 15, GitHubId = 0, Login = "Romaine45" },
                        new { Id = 16, GitHubId = 0, Login = "Maia_Borer" },
                        new { Id = 17, GitHubId = 0, Login = "Dallas.Gutmann" },
                        new { Id = 18, GitHubId = 0, Login = "Kellen.Beatty63" },
                        new { Id = 19, GitHubId = 0, Login = "Jaime.Schmitt" },
                        new { Id = 20, GitHubId = 0, Login = "Zachary52" },
                        new { Id = 21, GitHubId = 0, Login = "Abigale.Lind" },
                        new { Id = 22, GitHubId = 0, Login = "Ray_Bergnaum26" },
                        new { Id = 23, GitHubId = 0, Login = "Boris_Kunde74" },
                        new { Id = 24, GitHubId = 0, Login = "Georgette.Purdy" },
                        new { Id = 25, GitHubId = 0, Login = "Clint.Grady81" },
                        new { Id = 26, GitHubId = 0, Login = "Drew_Schaden" },
                        new { Id = 27, GitHubId = 0, Login = "Toy_Collier" },
                        new { Id = 28, GitHubId = 0, Login = "Mariano_Dickens55" },
                        new { Id = 29, GitHubId = 0, Login = "Brandon.Luettgen" },
                        new { Id = 30, GitHubId = 0, Login = "Marie92" },
                        new { Id = 31, GitHubId = 0, Login = "Emmie_Rohan42" },
                        new { Id = 32, GitHubId = 0, Login = "Terence.Schultz74" },
                        new { Id = 33, GitHubId = 0, Login = "Mafalda.Okuneva24" },
                        new { Id = 34, GitHubId = 0, Login = "Freddy.Haley73" },
                        new { Id = 35, GitHubId = 0, Login = "Dorian.Schultz" },
                        new { Id = 36, GitHubId = 0, Login = "Asia_Sipes" },
                        new { Id = 37, GitHubId = 0, Login = "Rosalind.Williamson" },
                        new { Id = 38, GitHubId = 0, Login = "Amira.Towne76" },
                        new { Id = 39, GitHubId = 0, Login = "Alfonzo71" },
                        new { Id = 40, GitHubId = 0, Login = "Bennett.Gorczany" },
                        new { Id = 41, GitHubId = 0, Login = "Zoe30" },
                        new { Id = 42, GitHubId = 0, Login = "Alivia.Walsh55" },
                        new { Id = 43, GitHubId = 0, Login = "Mackenzie65" },
                        new { Id = 44, GitHubId = 0, Login = "Lisandro_McLaughlin" },
                        new { Id = 45, GitHubId = 0, Login = "Stanley48" },
                        new { Id = 46, GitHubId = 0, Login = "Lela21" },
                        new { Id = 47, GitHubId = 0, Login = "Lauryn26" },
                        new { Id = 48, GitHubId = 0, Login = "Afton.Cummings" },
                        new { Id = 49, GitHubId = 0, Login = "Nolan51" },
                        new { Id = 50, GitHubId = 0, Login = "Leann67" },
                        new { Id = 51, GitHubId = 0, Login = "Vivianne45" },
                        new { Id = 52, GitHubId = 0, Login = "Reginald_Buckridge" },
                        new { Id = 53, GitHubId = 0, Login = "Shana83" },
                        new { Id = 54, GitHubId = 0, Login = "Eloy_Schaden" },
                        new { Id = 55, GitHubId = 0, Login = "Virgie_Boyer" },
                        new { Id = 56, GitHubId = 0, Login = "Maude.White" },
                        new { Id = 57, GitHubId = 0, Login = "Virginia_Champlin58" },
                        new { Id = 58, GitHubId = 0, Login = "Rhett41" },
                        new { Id = 59, GitHubId = 0, Login = "Jamarcus59" },
                        new { Id = 60, GitHubId = 0, Login = "Mac_Hudson" },
                        new { Id = 61, GitHubId = 0, Login = "Emelie95" },
                        new { Id = 62, GitHubId = 0, Login = "Melba_Satterfield1" },
                        new { Id = 63, GitHubId = 0, Login = "Karley.Lakin" },
                        new { Id = 64, GitHubId = 0, Login = "Wiley_Aufderhar48" },
                        new { Id = 65, GitHubId = 0, Login = "Matteo.Fahey5" },
                        new { Id = 66, GitHubId = 0, Login = "Johan_Bruen" },
                        new { Id = 67, GitHubId = 0, Login = "Dorian.Graham" },
                        new { Id = 68, GitHubId = 0, Login = "Meaghan.Windler56" },
                        new { Id = 69, GitHubId = 0, Login = "Eulah34" },
                        new { Id = 70, GitHubId = 0, Login = "Taurean.Smith" },
                        new { Id = 71, GitHubId = 0, Login = "Pierre48" },
                        new { Id = 72, GitHubId = 0, Login = "Jeramie.Crist69" },
                        new { Id = 73, GitHubId = 0, Login = "Dereck.Ziemann69" },
                        new { Id = 74, GitHubId = 0, Login = "Rose_Green41" },
                        new { Id = 75, GitHubId = 0, Login = "Leslie.Feeney60" },
                        new { Id = 76, GitHubId = 0, Login = "Laverna.Kling" },
                        new { Id = 77, GitHubId = 0, Login = "Danielle3" },
                        new { Id = 78, GitHubId = 0, Login = "Nils.Runte39" },
                        new { Id = 79, GitHubId = 0, Login = "Flavio55" },
                        new { Id = 80, GitHubId = 0, Login = "Calista_Adams40" },
                        new { Id = 81, GitHubId = 0, Login = "Darron_Nolan41" },
                        new { Id = 82, GitHubId = 0, Login = "Courtney.Jones99" },
                        new { Id = 83, GitHubId = 0, Login = "Estel.Jones53" },
                        new { Id = 84, GitHubId = 0, Login = "Lila_Wehner" },
                        new { Id = 85, GitHubId = 0, Login = "Vernice_Ernser" },
                        new { Id = 86, GitHubId = 0, Login = "Jamel_Tremblay" },
                        new { Id = 87, GitHubId = 0, Login = "Eda79" },
                        new { Id = 88, GitHubId = 0, Login = "Mateo21" },
                        new { Id = 89, GitHubId = 0, Login = "Wallace93" },
                        new { Id = 90, GitHubId = 0, Login = "Baby_Morar71" },
                        new { Id = 91, GitHubId = 0, Login = "Alysson_Witting" },
                        new { Id = 92, GitHubId = 0, Login = "Lamont65" },
                        new { Id = 93, GitHubId = 0, Login = "Norris67" },
                        new { Id = 94, GitHubId = 0, Login = "Maggie83" },
                        new { Id = 95, GitHubId = 0, Login = "Efren_Conn20" },
                        new { Id = 96, GitHubId = 0, Login = "Lucio_Metz56" },
                        new { Id = 97, GitHubId = 0, Login = "Antonina_Parker" },
                        new { Id = 98, GitHubId = 0, Login = "Eveline.Kautzer41" },
                        new { Id = 99, GitHubId = 0, Login = "Thora69" },
                        new { Id = 100, GitHubId = 0, Login = "Breana92" }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserFollowers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FollowerId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.ToTable("UserFollowers");
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Rating");

                    b.Property<int>("SkillId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");

                    b.HasData(
                        new { Id = 1, Rating = 0, SkillId = 14, UserId = 1 },
                        new { Id = 2, Rating = 1, SkillId = 3, UserId = 2 },
                        new { Id = 3, Rating = 2, SkillId = 23, UserId = 2 },
                        new { Id = 4, Rating = 3, SkillId = 11, UserId = 2 },
                        new { Id = 5, Rating = 5, SkillId = 1, UserId = 3 },
                        new { Id = 6, Rating = 3, SkillId = 7, UserId = 3 },
                        new { Id = 7, Rating = 2, SkillId = 19, UserId = 3 },
                        new { Id = 8, Rating = 2, SkillId = 20, UserId = 3 },
                        new { Id = 9, Rating = 0, SkillId = 12, UserId = 4 },
                        new { Id = 10, Rating = 0, SkillId = 2, UserId = 4 },
                        new { Id = 11, Rating = 3, SkillId = 17, UserId = 4 },
                        new { Id = 12, Rating = 4, SkillId = 13, UserId = 5 },
                        new { Id = 13, Rating = 3, SkillId = 3, UserId = 7 },
                        new { Id = 14, Rating = 0, SkillId = 14, UserId = 7 },
                        new { Id = 15, Rating = 4, SkillId = 7, UserId = 8 },
                        new { Id = 16, Rating = 5, SkillId = 1, UserId = 8 },
                        new { Id = 17, Rating = 1, SkillId = 19, UserId = 8 },
                        new { Id = 18, Rating = 3, SkillId = 1, UserId = 8 },
                        new { Id = 19, Rating = 0, SkillId = 4, UserId = 9 },
                        new { Id = 20, Rating = 2, SkillId = 18, UserId = 9 },
                        new { Id = 21, Rating = 0, SkillId = 17, UserId = 9 },
                        new { Id = 22, Rating = 0, SkillId = 1, UserId = 9 },
                        new { Id = 23, Rating = 5, SkillId = 16, UserId = 9 },
                        new { Id = 24, Rating = 3, SkillId = 20, UserId = 10 },
                        new { Id = 25, Rating = 2, SkillId = 22, UserId = 10 },
                        new { Id = 26, Rating = 3, SkillId = 19, UserId = 10 },
                        new { Id = 27, Rating = 0, SkillId = 11, UserId = 11 },
                        new { Id = 28, Rating = 2, SkillId = 6, UserId = 11 },
                        new { Id = 29, Rating = 2, SkillId = 21, UserId = 12 },
                        new { Id = 30, Rating = 2, SkillId = 9, UserId = 12 },
                        new { Id = 31, Rating = 1, SkillId = 16, UserId = 13 },
                        new { Id = 32, Rating = 0, SkillId = 8, UserId = 13 },
                        new { Id = 33, Rating = 0, SkillId = 23, UserId = 13 },
                        new { Id = 34, Rating = 1, SkillId = 19, UserId = 14 },
                        new { Id = 35, Rating = 0, SkillId = 22, UserId = 14 },
                        new { Id = 36, Rating = 5, SkillId = 7, UserId = 15 },
                        new { Id = 37, Rating = 4, SkillId = 18, UserId = 15 },
                        new { Id = 38, Rating = 5, SkillId = 14, UserId = 16 },
                        new { Id = 39, Rating = 4, SkillId = 21, UserId = 17 },
                        new { Id = 40, Rating = 2, SkillId = 21, UserId = 18 },
                        new { Id = 41, Rating = 5, SkillId = 9, UserId = 19 },
                        new { Id = 42, Rating = 1, SkillId = 15, UserId = 19 },
                        new { Id = 43, Rating = 3, SkillId = 2, UserId = 20 },
                        new { Id = 44, Rating = 0, SkillId = 24, UserId = 20 },
                        new { Id = 45, Rating = 4, SkillId = 15, UserId = 21 },
                        new { Id = 46, Rating = 0, SkillId = 14, UserId = 22 },
                        new { Id = 47, Rating = 2, SkillId = 6, UserId = 22 },
                        new { Id = 48, Rating = 5, SkillId = 15, UserId = 22 },
                        new { Id = 49, Rating = 4, SkillId = 25, UserId = 23 },
                        new { Id = 50, Rating = 5, SkillId = 16, UserId = 24 },
                        new { Id = 51, Rating = 1, SkillId = 12, UserId = 24 },
                        new { Id = 52, Rating = 2, SkillId = 9, UserId = 25 },
                        new { Id = 53, Rating = 2, SkillId = 12, UserId = 25 },
                        new { Id = 54, Rating = 0, SkillId = 2, UserId = 25 },
                        new { Id = 55, Rating = 1, SkillId = 4, UserId = 27 },
                        new { Id = 56, Rating = 3, SkillId = 18, UserId = 27 },
                        new { Id = 57, Rating = 1, SkillId = 1, UserId = 29 },
                        new { Id = 58, Rating = 0, SkillId = 5, UserId = 31 },
                        new { Id = 59, Rating = 0, SkillId = 22, UserId = 31 },
                        new { Id = 60, Rating = 0, SkillId = 1, UserId = 32 },
                        new { Id = 61, Rating = 3, SkillId = 6, UserId = 32 },
                        new { Id = 62, Rating = 0, SkillId = 20, UserId = 32 },
                        new { Id = 63, Rating = 3, SkillId = 23, UserId = 33 },
                        new { Id = 64, Rating = 0, SkillId = 22, UserId = 35 },
                        new { Id = 65, Rating = 0, SkillId = 4, UserId = 36 },
                        new { Id = 66, Rating = 4, SkillId = 10, UserId = 36 },
                        new { Id = 67, Rating = 4, SkillId = 9, UserId = 37 },
                        new { Id = 68, Rating = 0, SkillId = 13, UserId = 40 },
                        new { Id = 69, Rating = 1, SkillId = 5, UserId = 40 },
                        new { Id = 70, Rating = 4, SkillId = 8, UserId = 41 },
                        new { Id = 71, Rating = 2, SkillId = 9, UserId = 41 },
                        new { Id = 72, Rating = 1, SkillId = 23, UserId = 41 },
                        new { Id = 73, Rating = 1, SkillId = 1, UserId = 41 },
                        new { Id = 74, Rating = 5, SkillId = 5, UserId = 42 },
                        new { Id = 75, Rating = 2, SkillId = 6, UserId = 42 },
                        new { Id = 76, Rating = 1, SkillId = 25, UserId = 42 },
                        new { Id = 77, Rating = 2, SkillId = 4, UserId = 43 },
                        new { Id = 78, Rating = 1, SkillId = 22, UserId = 43 },
                        new { Id = 79, Rating = 2, SkillId = 13, UserId = 43 },
                        new { Id = 80, Rating = 4, SkillId = 22, UserId = 43 },
                        new { Id = 81, Rating = 4, SkillId = 8, UserId = 44 },
                        new { Id = 82, Rating = 5, SkillId = 7, UserId = 44 },
                        new { Id = 83, Rating = 0, SkillId = 8, UserId = 45 },
                        new { Id = 84, Rating = 1, SkillId = 6, UserId = 45 },
                        new { Id = 85, Rating = 0, SkillId = 6, UserId = 45 },
                        new { Id = 86, Rating = 5, SkillId = 11, UserId = 46 },
                        new { Id = 87, Rating = 3, SkillId = 23, UserId = 46 },
                        new { Id = 88, Rating = 1, SkillId = 8, UserId = 47 },
                        new { Id = 89, Rating = 4, SkillId = 2, UserId = 48 },
                        new { Id = 90, Rating = 5, SkillId = 20, UserId = 48 },
                        new { Id = 91, Rating = 0, SkillId = 19, UserId = 49 },
                        new { Id = 92, Rating = 5, SkillId = 18, UserId = 49 },
                        new { Id = 93, Rating = 1, SkillId = 16, UserId = 50 },
                        new { Id = 94, Rating = 0, SkillId = 1, UserId = 50 },
                        new { Id = 95, Rating = 1, SkillId = 13, UserId = 50 },
                        new { Id = 96, Rating = 2, SkillId = 19, UserId = 51 },
                        new { Id = 97, Rating = 0, SkillId = 25, UserId = 52 },
                        new { Id = 98, Rating = 5, SkillId = 2, UserId = 52 },
                        new { Id = 99, Rating = 1, SkillId = 6, UserId = 52 },
                        new { Id = 100, Rating = 1, SkillId = 11, UserId = 52 },
                        new { Id = 101, Rating = 1, SkillId = 7, UserId = 53 },
                        new { Id = 102, Rating = 0, SkillId = 18, UserId = 53 },
                        new { Id = 103, Rating = 4, SkillId = 18, UserId = 54 },
                        new { Id = 104, Rating = 0, SkillId = 7, UserId = 54 },
                        new { Id = 105, Rating = 0, SkillId = 8, UserId = 54 },
                        new { Id = 106, Rating = 0, SkillId = 13, UserId = 54 },
                        new { Id = 107, Rating = 4, SkillId = 1, UserId = 55 },
                        new { Id = 108, Rating = 5, SkillId = 24, UserId = 55 },
                        new { Id = 109, Rating = 5, SkillId = 12, UserId = 55 },
                        new { Id = 110, Rating = 5, SkillId = 12, UserId = 55 },
                        new { Id = 111, Rating = 5, SkillId = 25, UserId = 56 },
                        new { Id = 112, Rating = 4, SkillId = 19, UserId = 57 },
                        new { Id = 113, Rating = 1, SkillId = 5, UserId = 57 },
                        new { Id = 114, Rating = 3, SkillId = 18, UserId = 58 },
                        new { Id = 115, Rating = 2, SkillId = 24, UserId = 58 },
                        new { Id = 116, Rating = 4, SkillId = 10, UserId = 59 },
                        new { Id = 117, Rating = 1, SkillId = 13, UserId = 60 },
                        new { Id = 118, Rating = 2, SkillId = 20, UserId = 63 },
                        new { Id = 119, Rating = 1, SkillId = 11, UserId = 63 },
                        new { Id = 120, Rating = 4, SkillId = 5, UserId = 63 },
                        new { Id = 121, Rating = 1, SkillId = 20, UserId = 64 },
                        new { Id = 122, Rating = 5, SkillId = 13, UserId = 64 },
                        new { Id = 123, Rating = 3, SkillId = 9, UserId = 64 },
                        new { Id = 124, Rating = 2, SkillId = 14, UserId = 65 },
                        new { Id = 125, Rating = 1, SkillId = 19, UserId = 65 },
                        new { Id = 126, Rating = 0, SkillId = 20, UserId = 66 },
                        new { Id = 127, Rating = 1, SkillId = 16, UserId = 66 },
                        new { Id = 128, Rating = 2, SkillId = 25, UserId = 66 },
                        new { Id = 129, Rating = 5, SkillId = 6, UserId = 67 },
                        new { Id = 130, Rating = 1, SkillId = 21, UserId = 68 },
                        new { Id = 131, Rating = 5, SkillId = 2, UserId = 69 },
                        new { Id = 132, Rating = 3, SkillId = 23, UserId = 70 },
                        new { Id = 133, Rating = 5, SkillId = 21, UserId = 70 },
                        new { Id = 134, Rating = 4, SkillId = 8, UserId = 70 },
                        new { Id = 135, Rating = 0, SkillId = 25, UserId = 71 },
                        new { Id = 136, Rating = 2, SkillId = 10, UserId = 71 },
                        new { Id = 137, Rating = 0, SkillId = 23, UserId = 72 },
                        new { Id = 138, Rating = 0, SkillId = 4, UserId = 75 },
                        new { Id = 139, Rating = 1, SkillId = 18, UserId = 75 },
                        new { Id = 140, Rating = 4, SkillId = 6, UserId = 76 },
                        new { Id = 141, Rating = 4, SkillId = 7, UserId = 76 },
                        new { Id = 142, Rating = 3, SkillId = 19, UserId = 76 },
                        new { Id = 143, Rating = 4, SkillId = 5, UserId = 76 },
                        new { Id = 144, Rating = 1, SkillId = 2, UserId = 77 },
                        new { Id = 145, Rating = 2, SkillId = 24, UserId = 79 },
                        new { Id = 146, Rating = 5, SkillId = 4, UserId = 79 },
                        new { Id = 147, Rating = 2, SkillId = 5, UserId = 80 },
                        new { Id = 148, Rating = 4, SkillId = 8, UserId = 80 },
                        new { Id = 149, Rating = 0, SkillId = 22, UserId = 80 },
                        new { Id = 150, Rating = 4, SkillId = 24, UserId = 80 },
                        new { Id = 151, Rating = 0, SkillId = 15, UserId = 81 },
                        new { Id = 152, Rating = 5, SkillId = 6, UserId = 81 },
                        new { Id = 153, Rating = 0, SkillId = 4, UserId = 82 },
                        new { Id = 154, Rating = 0, SkillId = 25, UserId = 82 },
                        new { Id = 155, Rating = 1, SkillId = 13, UserId = 83 },
                        new { Id = 156, Rating = 0, SkillId = 13, UserId = 84 },
                        new { Id = 157, Rating = 5, SkillId = 16, UserId = 84 },
                        new { Id = 158, Rating = 1, SkillId = 2, UserId = 86 },
                        new { Id = 159, Rating = 3, SkillId = 3, UserId = 87 },
                        new { Id = 160, Rating = 1, SkillId = 18, UserId = 87 },
                        new { Id = 161, Rating = 2, SkillId = 17, UserId = 87 },
                        new { Id = 162, Rating = 5, SkillId = 6, UserId = 87 },
                        new { Id = 163, Rating = 4, SkillId = 12, UserId = 88 },
                        new { Id = 164, Rating = 5, SkillId = 2, UserId = 88 },
                        new { Id = 165, Rating = 2, SkillId = 13, UserId = 88 },
                        new { Id = 166, Rating = 5, SkillId = 24, UserId = 88 },
                        new { Id = 167, Rating = 5, SkillId = 10, UserId = 89 },
                        new { Id = 168, Rating = 3, SkillId = 1, UserId = 89 },
                        new { Id = 169, Rating = 4, SkillId = 23, UserId = 89 },
                        new { Id = 170, Rating = 5, SkillId = 7, UserId = 89 },
                        new { Id = 171, Rating = 2, SkillId = 2, UserId = 90 },
                        new { Id = 172, Rating = 1, SkillId = 4, UserId = 90 },
                        new { Id = 173, Rating = 3, SkillId = 23, UserId = 91 },
                        new { Id = 174, Rating = 1, SkillId = 16, UserId = 91 },
                        new { Id = 175, Rating = 5, SkillId = 19, UserId = 92 },
                        new { Id = 176, Rating = 1, SkillId = 20, UserId = 92 },
                        new { Id = 177, Rating = 2, SkillId = 24, UserId = 92 },
                        new { Id = 178, Rating = 0, SkillId = 24, UserId = 93 },
                        new { Id = 179, Rating = 2, SkillId = 9, UserId = 93 },
                        new { Id = 180, Rating = 2, SkillId = 13, UserId = 93 },
                        new { Id = 181, Rating = 2, SkillId = 12, UserId = 93 },
                        new { Id = 182, Rating = 3, SkillId = 19, UserId = 94 },
                        new { Id = 183, Rating = 0, SkillId = 18, UserId = 94 },
                        new { Id = 184, Rating = 4, SkillId = 1, UserId = 95 },
                        new { Id = 185, Rating = 3, SkillId = 22, UserId = 95 },
                        new { Id = 186, Rating = 4, SkillId = 13, UserId = 96 },
                        new { Id = 187, Rating = 2, SkillId = 1, UserId = 97 },
                        new { Id = 188, Rating = 1, SkillId = 6, UserId = 97 },
                        new { Id = 189, Rating = 4, SkillId = 6, UserId = 97 },
                        new { Id = 190, Rating = 4, SkillId = 20, UserId = 99 },
                        new { Id = 191, Rating = 3, SkillId = 20, UserId = 99 },
                        new { Id = 192, Rating = 0, SkillId = 19, UserId = 100 },
                        new { Id = 193, Rating = 5, SkillId = 7, UserId = 100 },
                        new { Id = 194, Rating = 0, SkillId = 1, UserId = 100 },
                        new { Id = 195, Rating = 3, SkillId = 4, UserId = 100 }
                    );
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectMember", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collaboo.App.WebAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.ProjectRequirement", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Project")
                        .WithMany("Requirements")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Collaboo.App.WebAPI.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserFollowers", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Follower", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Collaboo.App.WebAPI.Entities.UserSkills", b =>
                {
                    b.HasOne("Collaboo.App.WebAPI.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Collaboo.App.WebAPI.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
